import { useHolderGate } from "../lib/holder-access";
import { validateWalletActionIntent, walletPromptRejected } from "./AgentWalletActions";
import { recordSubmitted } from "../lib/transactions";
import { useCallback, useEffect, useState } from "react";
import { isAddress } from "viem";
import type { RuntimeAgent, WalletActionIntent } from "../lib/api";
import type { AccountAPI } from "../lib/jobs";
import { usdtUnits } from "../lib/amounts";
import { BNB_CHAIN_ID, USDT_ADDRESS, explorer, sameAddress, waitForTransaction, type EvmTransaction } from "../lib/evm";
import type { PaymentSystem } from "../lib/payments";

function cachedCredit(key:string){try{return JSON.parse(localStorage.getItem(key)||"null") as {id:string;hash:string;intent?:CreditIntent;uncertain?:boolean}|null;}catch{return null;}}
function rememberCredit(key:string,value:{id:string;hash:string;intent?:CreditIntent;uncertain?:boolean}|null){try{if(value)localStorage.setItem(key,JSON.stringify(value));else localStorage.removeItem(key);}catch{ /* Keep the submitted hash in component state. */ }}
const blankPayment={recipient:"",tool:"",request:"",receipt:""};
type Credit = {id:string;agent_id:string;onchain_agent_id:string;lender:string;borrower:string;signer:string;role:"lender"|"borrower";funded:string;available:string;outstanding:string;total_spent:string;total_repaid:string;withdrawn:string;per_call:string;daily_cap:string;expires_at:number;tools:string[];recipients:string[];accepted:boolean;closed:boolean;status:string;interest_bps:number;secured:boolean;collateral?:{token:string;decimals:number;amount:string;value_usdt:string|null;borrowing_power_usdt:string|null;available_borrowing_usdt:string|null;health_factor:string|null;oracle_status:string;ltv_bps:number;liquidation_bps:number;bonus_bps:number;paused:boolean};actions:{pledge?:boolean;withdraw_collateral?:boolean;liquidate?:boolean;accept:boolean;repay:boolean;withdraw:boolean;close:boolean;spend:boolean}};
type CreditAsset = {address:string;symbol:string;decimals:number;borrowing_enabled:boolean;borrowing_status:string;risk?:{ltvBps:number;liquidationBps:number;bonusBps:number}|null};
type CreditAssets = {chain_id:number;currency:string;assets:CreditAsset[]};
const creditAction = (action:string) => action.endsWith("_credit") || ["pledge_collateral","withdraw_collateral"].includes(action);
function units(value:string, decimals:number) { const scaled=usdtUnits(value); if(scaled===null || !Number.isInteger(decimals) || decimals<0 || decimals>18 || scaled % (10n ** BigInt(18-decimals)) !== 0n) return null; return scaled / (10n ** BigInt(18-decimals)); }
type CreditIntent=WalletActionIntent&{tx_hash?:string|null};
type CreditData = {chain_id:number;currency:string;agreements:Credit[];pending_intents:CreditIntent[]};
export function AgentCredit({agent,owned,api,live,send,changed,initialTarget}:{agent:RuntimeAgent;owned:RuntimeAgent[];api:AccountAPI;live:boolean;send:(sender:string,transactions:EvmTransaction[])=>Promise<string>;changed:()=>Promise<void>;initialTarget?:string}) {
  const access = useHolderGate();
  const [assets,setAssets]=useState<CreditAsset[]>([]),[collateralToken,setCollateralToken]=useState(USDT_ADDRESS);
  const [collateralAmounts,setCollateralAmounts]=useState<Record<string,string>>({}),[minimums,setMinimums]=useState<Record<string,string>>({});
  const [spend,setSpend]=useState<Record<string,{recipient:string;tool:string;request:string;receipt:string}>>({});
  const [choices,setChoices]=useState<{id:string;name:string;status:string}[]>(owned);
  const [data,setData]=useState<CreditData|null>(null),[system,setSystem]=useState<PaymentSystem|null>(null),[pending,setPending]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[intent,setIntent]=useState<CreditIntent|null>(null),[hash,setHash]=useState("");
  const [target,setTarget]=useState(initialTarget||agent.id),[signer,setSigner]=useState(""),[amount,setAmount]=useState(String(agent.daily_cap)),[perCall,setPerCall]=useState(String(agent.max_call)),[dailyCap,setDailyCap]=useState(String(agent.daily_cap)),[hours,setHours]=useState("24"),[recipients,setRecipients]=useState<string[]>([]),[tools,setTools]=useState<string[]>(agent.tools),[actionAmounts,setActionAmounts]=useState<Record<string,string>>({});
  const storageKey=`tab:credit:pending:${agent.id}`;
  const hasPending=Boolean(intent||data?.pending_intents.length||cachedCredit(`tab:wallet:pending:${agent.id}`));
  const wasSubmitted=Boolean(intent?.tx_hash||(intent&&cachedCredit(storageKey)?.id===intent.id));
  const refresh=useCallback(async()=>{const [d,s,publicAgents,collateral]=await Promise.all([api<CreditData>(`/account/runtime/${agent.id}/credit`),api<PaymentSystem>("/x402/system"),api<{id:string;name:string;status:string}[]>("/agents/live"),api<CreditAssets>("/credit/assets")]);if(collateral.chain_id!==BNB_CHAIN_ID||collateral.currency!=="USDT")throw Error("Collateral belongs to another network.");setAssets(collateral.assets);setChoices([...new Map([...publicAgents,...owned.filter(a=>a.registry_id&&a.wallet)].map(a=>[a.id,a])).values()]);if(d.chain_id!==BNB_CHAIN_ID||d.currency!=="USDT")throw Error("Credit data belongs to another network.");setData(d);setSystem(s);const record=cachedCredit(storageKey);const creditPending=d.pending_intents.filter(i=>creditAction(i.action));const next=creditPending.find(i=>i.id===record?.id)||creditPending[0]||record?.intent||null;setIntent(next);if(next&&(next.tx_hash||record?.id===next.id))setHash(next.tx_hash||record!.hash);else if(!next){rememberCredit(storageKey,null);setHash("");}},[api,agent.id,storageKey,owned]);
  useEffect(()=>{const update=()=>{if(live)void refresh().catch(e=>setError(e.message));};update();window.addEventListener("tab:wallet-actions-changed",update);return()=>window.removeEventListener("tab:wallet-actions-changed",update);},[live,refresh]);
  async function act(action:()=>Promise<void>){setPending(true);setError("");setNotice("");try{await action();}catch(e){setError((e as Error).message);}finally{setPending(false);}}
  function validateCreditIntent(next:WalletActionIntent, expected?:Record<string,unknown>) {
    let token=USDT_ADDRESS,decimals=18;
    if(["pledge_collateral","withdraw_collateral","liquidate_credit"].includes(next.action)) {
      const credit=data?.agreements.find(c=>c.id===next.details.credit_id),collateral=credit?.collateral;
      if(!collateral||!sameAddress(collateral.token,String(next.details.token_address)))throw Error("The collateral differs from this agreement.");
      if(next.action==="pledge_collateral"||next.action==="withdraw_collateral") {token=collateral.token;decimals=collateral.decimals;}
      if(next.action==="liquidate_credit" && (units(String(next.details.minimum_collateral_out),collateral.decimals)??0n)<=0n)throw Error("Set an exact minimum collateral return.");
    }
    validateWalletActionIntent(next,agent,token,decimals,expected,true);
  }
  async function prepare(body:Record<string,unknown>){await access.require(String(body.action),body);const next=await api<WalletActionIntent>(`/account/runtime/${agent.id}/wallet-actions/prepare`,{method:"POST",body:JSON.stringify(body)});validateCreditIntent(next,body);setIntent(next);setHash("");window.dispatchEvent(new Event("tab:wallet-actions-changed"));}
  async function confirm(transactionHash:string){if(!intent)return;await recordSubmitted(api,`/account/wallet-actions/${intent.id}/submitted`,transactionHash);const result=await api<{status:string}>(`/account/wallet-actions/${intent.id}/confirm`,{method:"POST",body:JSON.stringify({tx_hash:transactionHash})});if(result.status!=="confirmed")throw Error("The credit transaction is not confirmed yet.");rememberCredit(storageKey,null);setIntent(null);setHash("");setNotice("Credit transaction confirmed.");window.dispatchEvent(new Event("tab:wallet-actions-changed"));await Promise.all([refresh(),changed()]);}
  function validateOpen(){if(!assets.some(a=>sameAddress(a.address,collateralToken)&&a.borrowing_enabled))throw Error("Choose collateral with verified borrowing support.");const total=usdtUnits(amount),per=usdtUnits(perCall),daily=usdtUnits(dailyCap),maxPer=usdtUnits(String(agent.max_call)),maxDay=usdtUnits(String(agent.daily_cap));if(total===null||per===null||daily===null||maxPer===null||maxDay===null||total<=0n||per<=0n||daily<=0n||per>maxPer||daily>maxDay||per>daily||daily>total||total>daily*7n)throw Error("Keep limits within the agent's policy. Fund at least one daily cap and at most seven.");if(!isAddress(signer,{strict:false})||!recipients.length||!tools.length||!/^\d+$/.test(hours)||Number(hours)<1||Number(hours)>168)throw Error("Choose a signer, approved tools and recipients, and an expiry from 1 to 168 hours.");}
  return <div className="paid-tool" data-testid="agent-credit"><h3>secured USDT credit</h3><p>Fund approved tool payments at zero interest. The borrower pledges collateral before spending. The agreement limits recipients, tools and amounts; a falling collateral value or overdue debt can trigger liquidation.</p>
    {!live?<p className="muted">Credit opens when the BNB Chain contracts are verified.</p>:<>
      {hasPending&&!intent&&<p className="field-help">Finish the pending wallet action below before preparing credit changes.</p>}
      {data?.agreements.map(credit=><div className="credit-agreement" key={credit.id}><h4>{credit.role} · {credit.status}</h4><p>{credit.available} USDT available · {credit.outstanding} USDT owed</p><details><summary>agreement terms</summary><p className="wallet-address">agreement {credit.id}</p><p className="wallet-address">lender {credit.lender}</p><p className="wallet-address">borrower {credit.borrower}</p><p className="wallet-address">signer {credit.signer}</p><p>{credit.funded} USDT funded · {credit.per_call} per call · {credit.daily_cap} per day</p><p>expires {new Date(credit.expires_at*1000).toLocaleString()} · zero interest · {credit.secured?"collateralized":"legacy agreement"}</p><p>tools: {credit.tools.join(", ")}</p>{credit.recipients.map(r=><p className="wallet-address" key={r}>recipient {r}</p>)}</details>
        {credit.collateral&&<div className="credit-collateral">
          <p>{credit.collateral.amount} {assets.find(a=>sameAddress(a.address,credit.collateral!.token))?.symbol||"collateral tokens"} pledged · {credit.collateral.available_borrowing_usdt??"unavailable"} USDT available to spend</p>
          <p className="field-help">borrow up to {credit.collateral.ltv_bps/100}% of collateral value · liquidation threshold {credit.collateral.liquidation_bps/100}% · health {credit.collateral.health_factor??(credit.outstanding==="0"?"no debt":"unavailable")}</p>
          {credit.collateral.oracle_status!=="verified"&&<p className="field-help">Collateral pricing is unavailable. Repayment and withdrawal after full repayment remain available.</p>}
          {(credit.actions.pledge||credit.actions.withdraw_collateral)&&<><label>collateral amount<input aria-label={`Collateral amount for ${credit.id}`} inputMode="decimal" value={collateralAmounts[credit.id]||""} onChange={e=>setCollateralAmounts(v=>({...v,[credit.id]:e.target.value}))}/></label><div className="agent-action-row">{(["pledge","withdraw_collateral"] as const).filter(action=>credit.actions[action]).map(action=><button type="button" className="outline" disabled={pending||hasPending||!access.allows(action==="pledge"?"pledge_collateral":"withdraw_collateral")} key={action} onClick={()=>void act(async()=>{const amount=collateralAmounts[credit.id]||"",value=units(amount,credit.collateral!.decimals);if(value===null||value<=0n)throw Error("Enter an exact positive collateral amount.");if(action==="withdraw_collateral"&&value>(units(credit.collateral!.amount,credit.collateral!.decimals)??0n))throw Error("The withdrawal exceeds your pledge.");await prepare({action:action==="pledge"?"pledge_collateral":"withdraw_collateral",credit_id:credit.id,token_address:credit.collateral!.token,amount});})}>{action==="pledge"?"pledge collateral":"withdraw collateral"}</button>)}</div></>}
          {credit.actions.liquidate&&<details><summary>liquidate overdue or undercollateralized debt</summary><p>Repay USDT to the lender and receive collateral with a {credit.collateral.bonus_bps/100}% bonus. Review the minimum return before signing.</p><label>USDT to repay<input inputMode="decimal" value={actionAmounts[credit.id]||""} onChange={e=>setActionAmounts(v=>({...v,[credit.id]:e.target.value}))}/></label><label>minimum collateral received<input inputMode="decimal" value={minimums[credit.id]||""} onChange={e=>setMinimums(v=>({...v,[credit.id]:e.target.value}))}/></label><button className="outline" disabled={pending||hasPending} onClick={()=>void act(async()=>{const amount=actionAmounts[credit.id]||"",minimum=minimums[credit.id]||"",value=usdtUnits(amount);if(value===null||value<=0n||value>(usdtUnits(credit.outstanding)??0n)||(units(minimum,credit.collateral!.decimals)??0n)<=0n)throw Error("Enter a repayment within the debt and an exact positive minimum collateral return.");await prepare({action:"liquidate_credit",credit_id:credit.id,token_address:credit.collateral!.token,amount,minimum_collateral_out:minimum});})}>review liquidation</button></details>}
        </div>}
        {(credit.actions.repay||credit.actions.withdraw)&&<label>amount in USDT<input aria-label={`Amount for ${credit.id}`} inputMode="decimal" value={actionAmounts[credit.id]||""} placeholder={credit.actions.repay?credit.outstanding:credit.available} onChange={e=>setActionAmounts(v=>({...v,[credit.id]:e.target.value}))}/></label>}
        <div className="agent-action-row">{(["accept","repay","withdraw","close"] as const).filter(action=>credit.actions[action]).map(action=><button className="outline" key={action} disabled={pending||hasPending||!access.allows(`${action}_credit`)} onClick={()=>act(async()=>{const amount=actionAmounts[credit.id]||"0";if(action==="repay"||action==="withdraw"){const value=usdtUnits(amount),max=usdtUnits(action==="repay"?credit.outstanding:credit.available);if(value===null||max===null||value<=0n||value>max)throw Error(`Enter an amount up to ${action==="repay"?credit.outstanding:credit.available} USDT.`);}await prepare({action:`${action}_credit`,credit_id:credit.id,amount});})}>{action} credit</button>)}</div>
        {credit.actions.spend&&<details><summary>authorized merchant payment</summary><form className="policy-fields" onSubmit={event=>{event.preventDefault();void act(async()=>{const value=usdtUnits(actionAmounts[credit.id]||""),available=usdtUnits(credit.available)??0n,cap=usdtUnits(credit.per_call)??0n,terms=spend[credit.id];if(value===null||value<=0n||value>available||value>cap)throw Error("Keep the USDT payment within the available balance and per-call cap.");if(!terms||!credit.recipients.includes(terms.recipient)||!credit.tools.includes(terms.tool)||![terms.request,terms.receipt].every(hash=>/^0x[0-9a-fA-F]{64}$/.test(hash)&&!/^0x0{64}$/.test(hash)))throw Error("Choose an approved recipient and tool, with nonzero 32-byte request and receipt commitments.");await prepare({action:"spend_credit",credit_id:credit.id,amount:actionAmounts[credit.id],recipient:terms.recipient,tool:terms.tool,request_hash:terms.request,receipt_hash:terms.receipt});});}}>
          <p>This contract payment transfers USDT and records your commitments. It does not retrieve an x402 response or verify that a provider delivered the service.</p>
          <label>credit payment amount · USDT<input inputMode="decimal" value={actionAmounts[credit.id]||""} onChange={e=>setActionAmounts(v=>({...v,[credit.id]:e.target.value}))}/></label>
          <label>approved merchant<select aria-label="Credit payment recipient" value={spend[credit.id]?.recipient||""} onChange={e=>setSpend(v=>({...v,[credit.id]:{...blankPayment,...v[credit.id],recipient:e.target.value}}))}><option value="">choose a recipient</option>{credit.recipients.map(value=><option key={value} value={value}>{value}</option>)}</select></label>
          <label>approved tool<select aria-label="Credit payment tool" value={spend[credit.id]?.tool||""} onChange={e=>setSpend(v=>({...v,[credit.id]:{...blankPayment,...v[credit.id],tool:e.target.value}}))}><option value="">choose a tool</option>{credit.tools.map(value=><option key={value} value={value}>{value}</option>)}</select></label>
          <label>request commitment<input placeholder="0x…" value={spend[credit.id]?.request||""} onChange={e=>setSpend(v=>({...v,[credit.id]:{...blankPayment,...v[credit.id],request:e.target.value}}))}/></label>
          <label>receipt commitment<input placeholder="0x…" value={spend[credit.id]?.receipt||""} onChange={e=>setSpend(v=>({...v,[credit.id]:{...blankPayment,...v[credit.id],receipt:e.target.value}}))}/></label><button className="outline" disabled={pending||hasPending||!access.allows("spend_credit")}>review merchant payment</button>
        </form></details>}
      </div>)}
      <button className="text-link" disabled={pending} onClick={()=>act(refresh)}>refresh credit</button>
      {data&&data.agreements.length===0&&<p className="muted">No credit agreements for this wallet.</p>}
      {!system?<p className="muted">{error?"Approved recipient status is unavailable.":"Checking approved recipients…"}</p>:!system.merchants.length?<p className="muted">New credit needs an approved USDT payment provider. None are connected yet.</p>:<details><summary>open a credit agreement</summary><form className="policy-fields" onSubmit={e=>{e.preventDefault();void act(async()=>{validateOpen();await prepare({action:"open_credit",target_agent_id:target,session_signer:signer,token_address:collateralToken,amount,per_call:perCall,daily_cap:dailyCap,session_expires_at:Math.floor(Date.now()/1000)+Number(hours)*3600,tools,recipients});});}}>
        <label>borrower agent<select value={target} onChange={e=>setTarget(e.target.value)}>{choices.filter(a=>["ready","paused"].includes(a.status)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><p className="field-help">The borrower accepts these terms with the wallet that owns the selected agent.</p>
        <label>collateral token<select value={collateralToken} onChange={e=>setCollateralToken(e.target.value)}>{assets.filter(a=>a.borrowing_enabled).map(a=><option key={a.address} value={a.address}>{a.symbol}</option>)}</select></label><p className="field-help">The borrower pledges this asset after accepting. Deposits in the separate backing vault do not automatically secure this agreement.</p>
        <label>authorized payment signer<input value={signer} placeholder="0x…" spellCheck={false} onChange={e=>setSigner(e.target.value)}/></label>
        <label>funding in USDT<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>USDT per call<input inputMode="decimal" value={perCall} onChange={e=>setPerCall(e.target.value)}/></label><label>USDT per day<input inputMode="decimal" value={dailyCap} onChange={e=>setDailyCap(e.target.value)}/></label><label>expires in hours<input inputMode="numeric" value={hours} onChange={e=>setHours(e.target.value)}/></label>
        <fieldset><legend>approved tools</legend>{agent.tools.map(tool=><label className="checkbox-row" key={tool}><input type="checkbox" checked={tools.includes(tool)} onChange={e=>setTools(values=>e.target.checked?[...values,tool]:values.filter(v=>v!==tool))}/>{tool}</label>)}</fieldset>
        <fieldset><legend>approved recipients</legend>{Array.from(new Map(system.merchants.map(m=>[m.recipient.toLowerCase(),m])).values()).map(m=><label className="checkbox-row" key={m.recipient}><input type="checkbox" checked={recipients.includes(m.recipient)} onChange={e=>setRecipients(values=>e.target.checked?[...values,m.recipient]:values.filter(v=>v!==m.recipient))}/><span>{m.id}<small className="wallet-address">{m.recipient}</small></span></label>)}</fieldset>
        <p className="field-help">Opening credit transfers this USDT to the contract. The lender can close future spending and withdraw unused funds. Closing does not erase money already owed.</p><button className="outline" disabled={pending||hasPending||!access.allows("open_credit")||agent.status!=="ready"||!assets.some(a=>a.borrowing_enabled)}>review credit terms</button>
      </form></details>}
      {intent&&<div className="payment-quote"><h4>review {intent.action.replaceAll("_"," ")}</h4><p>BNB Smart Chain · wallet <span className="wallet-address">{intent.sender}</span></p><p>{intent.transactions.length} wallet transaction{intent.transactions.length===1?"":"s"}; approvals are limited to this action.</p><details><summary>transaction details</summary><pre className="run-output">{JSON.stringify(intent.details,null,2)}</pre></details>
        {!hash&&!wasSubmitted&&<button className="primary" disabled={pending||new Date(intent.expires_at).getTime()<=Date.now()||!access.allows(intent.action,intent.details)} onClick={()=>act(async()=>{await access.require(intent.action,intent.details,intent.sender);validateCreditIntent(intent);if(Date.parse(intent.expires_at)<=Date.now())throw Error("This unsigned action has expired. Refresh before reviewing it again.");rememberCredit(storageKey,{id:intent.id,hash:"",intent,uncertain:true});let transactionHash:string;try{transactionHash=await send(intent.sender,intent.transactions);}catch(error){if(walletPromptRejected(error))rememberCredit(storageKey,null);throw error;}setHash(transactionHash);rememberCredit(storageKey,{id:intent.id,hash:transactionHash,intent});await recordSubmitted(api,`/account/wallet-actions/${intent.id}/submitted`,transactionHash);await waitForTransaction(transactionHash);await confirm(transactionHash);})}>confirm in wallet</button>}
        {wasSubmitted&&!hash&&<p className="field-help">The wallet interaction may have submitted the final action. Check wallet activity and paste its transaction hash before preparing another action.</p>}
        <label>submitted transaction hash<input value={hash} onChange={e=>setHash(e.target.value)} placeholder="0x…" spellCheck={false}/></label><p className="field-help">If a transaction was submitted, verify it here before preparing another action.</p><button className="outline" disabled={pending||!/^0x[0-9a-fA-F]{64}$/.test(hash)} onClick={()=>act(()=>confirm(hash))}>verify credit transaction</button>{hash&&<button className="outline" disabled={pending} onClick={()=>act(async()=>{await recordSubmitted(api,`/account/wallet-actions/${intent.id}/submitted`,hash);await api(`/account/wallet-actions/${intent.id}/release-failed`,{method:"POST"});rememberCredit(storageKey,null);setIntent(null);setHash("");window.dispatchEvent(new Event("tab:wallet-actions-changed"));await refresh();setNotice("Failed transaction verified. You can review a new action.");})}>check failed transaction</button>}{hash&&<a href={explorer(hash)} target="_blank" rel="noreferrer"> view transaction ↗</a>}
      </div>}
    </>}
    {notice&&<p role="status">{notice}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
  </div>;
}
