import { useCallback, useEffect, useState } from "react";
import { decodeFunctionData, erc20Abi, isAddress, keccak256, stringToHex } from "viem";
import type { BackingAsset, Bounty, Job, PublicJob, RuntimeAgent, TokenSystem, WalletActionIntent } from "../lib/api";
import type { AccountAPI } from "../lib/jobs";
import type { PaymentSystem } from "../lib/payments";
import { usdtUnits } from "../lib/amounts";
import { NoWalletSubmissionError, BNB_CHAIN_ID, USDT_ADDRESS, explorer, sameAddress, validateTransaction, waitForTransaction, type EvmTransaction } from "../lib/evm";
import { recordSubmitted } from "../lib/transactions";

const actions = {
  deploy_token: ["agent token", "create an agent token"], pair_token: ["agent token", "pair an existing token"],
  back: ["backing", "deposit a backing token"], withdraw_backing: ["backing", "withdraw a backing token"], back_bnb: ["backing", "deposit BNB backing"], withdraw_bnb: ["backing", "withdraw BNB backing"],
  fund_spending: ["spending", "fund the agent's USDT spending"], withdraw_spending: ["spending", "withdraw unused USDT"], pause_agent: ["spending", "pause or resume onchain spending"],
  grant_session: ["payment permissions", "authorize a payment signer"], revoke_session: ["payment permissions", "revoke a payment signer"], session_pay: ["payment permissions", "make an authorized merchant payment"],
  bind_job_agent: ["jobs", "bind this agent to a funded job"], bond_job: ["jobs", "post the published job bond"], settle_bond: ["jobs", "settle a completed job bond"],
  fund_bounty: ["bounties", "fund a bounty draft"], claim_bounty: ["bounties", "claim a funded bounty"],
  stake: ["official TAB", "stake TAB"], unstake: ["official TAB", "withdraw unlocked TAB"],
  open_outcome: ["job outcomes", "open a job outcome pool"], bet_outcome: ["job outcomes", "take a job outcome position"], resolve_outcome: ["job outcomes", "resolve a job outcome"], claim_outcome: ["job outcomes", "claim an outcome payout"],
} as const;
type Action = keyof typeof actions;
const actionKeys = Object.keys(actions) as Action[];
const officialActions = new Set<Action>(["stake", "unstake", "claim_bounty", "open_outcome", "bet_outcome", "resolve_outcome", "claim_outcome"]);
const recoveryActions = new Set<Action>(["withdraw_bnb", "withdraw_backing", "withdraw_spending", "unstake", "settle_bond", "resolve_outcome", "claim_outcome", "revoke_session", "pause_agent"]);
const jobActions = new Set<Action>(["bind_job_agent", "bond_job", "settle_bond", "open_outcome", "bet_outcome", "resolve_outcome", "claim_outcome"]);
const amountActions = new Set<Action>(["deploy_token", "back", "withdraw_backing", "back_bnb", "withdraw_bnb", "fund_spending", "withdraw_spending", "stake", "grant_session", "session_pay", "bet_outcome"]);
const credits = (action: string) => action.endsWith("_credit") || ["pledge_collateral","withdraw_collateral"].includes(action) || action.startsWith("finance_");
const changedEvent = () => window.dispatchEvent(new Event("tab:wallet-actions-changed"));
type Pending = { intent: WalletActionIntent; hash: string; uncertain: boolean };
function saved(key: string): Pending | null { try { return JSON.parse(localStorage.getItem(key) || "null") as Pending | null; } catch { return null; } }
function remember(key: string, value: Pending | null) { try { if (value) localStorage.setItem(key, JSON.stringify(value)); else localStorage.removeItem(key); } catch { /* Keep the intent and hash in component state. */ } }
function exactAmount(value: string, decimals = 18, zero = false) { const units = usdtUnits(value); if (units === null || (!zero && units <= 0n) || (value.split(".")[1]?.length || 0) > decimals) throw Error(`Enter an exact ${zero ? "nonnegative" : "positive"} amount with at most ${decimals} decimals.`); return units; }
export function walletPromptRejected(error: unknown) { let item: unknown = error; for (let i = 0; i < 8 && item && typeof item === "object"; i++) { const cause = item as {code?:number;name?:string;cause?:unknown}; if (item instanceof NoWalletSubmissionError || cause.code === 4001 || cause.name === "UserRejectedRequestError") return true; item = cause.cause; } return false; }
function validHash(value: string) { return /^0x[0-9a-fA-F]{64}$/.test(value) && !/^0x0{64}$/.test(value); }
function validNonce(value: string) { return /^\d+$/.test(value) && BigInt(value) <= 18446744073709551615n; }

/** Guard the actual wallet payload again immediately before requesting a signature. */
export function validateWalletActionIntent(intent: WalletActionIntent, agent: RuntimeAgent, approvedToken?: string | null, decimals = 18, expected?: Record<string, unknown>, allowCredit = false) {
  if (intent.chain_id !== BNB_CHAIN_ID || intent.agent_id !== agent.id || !sameAddress(intent.sender, agent.wallet)) throw Error("This action belongs to another agent, wallet, or network.");
  if (!actionKeys.includes(intent.action as Action) && !(allowCredit && ["open_credit","accept_credit","repay_credit","withdraw_credit","close_credit","spend_credit","pledge_collateral","withdraw_collateral","liquidate_credit"].includes(intent.action))) throw Error("Review this action in its credit panel.");
  if (!Number.isFinite(Date.parse(intent.expires_at)) || Date.parse(intent.expires_at) <= Date.now()) throw Error("This unsigned preparation expired. Refresh before requesting another wallet signature.");
  if (!intent.transactions.length || intent.transactions.length > 3) throw Error("Unexpected wallet transaction sequence.");
  if (expected && Object.entries(expected).some(([key, value]) => JSON.stringify(intent.details[key]) !== JSON.stringify(value))) throw Error("The prepared action changed the terms you entered. Refresh and review it again.");
  const final = intent.transactions.at(-1)!;
  intent.transactions.forEach(validateTransaction);
  if (!sameAddress(final.to, intent.to) || final.data.toLowerCase() !== intent.data.toLowerCase() || BigInt(final.value) !== BigInt(intent.value)) throw Error("The final transaction differs from the reviewed action.");
  if (intent.transaction && (!sameAddress(intent.transaction.to, final.to) || intent.transaction.data.toLowerCase() !== final.data.toLowerCase() || BigInt(intent.transaction.value) !== BigInt(final.value))) throw Error("The transaction summary does not match the wallet request.");
  const amount = typeof intent.details.amount === "string" ? usdtUnits(intent.details.amount) : null;
  if (intent.action === "back_bnb") { if (amount === null || BigInt(final.value) !== amount) throw Error("The BNB deposit does not match the reviewed amount."); }
  else if (BigInt(final.value) !== 0n) throw Error("This action must not transfer native BNB beyond network fees.");
  if (!Number.isInteger(decimals) || decimals < 0 || decimals > 18) throw Error("The token precision is invalid.");
  const scale = 10n ** BigInt(18 - decimals);
  if (intent.transactions.length > 1 && (amount === null || amount % scale !== 0n)) throw Error("The approval amount exceeds the token precision.");
  const approvals = intent.transactions.slice(0, -1);
  for (let index = 0; index < approvals.length; index++) {
    const approval = approvals[index];
    if (!approvedToken || !sameAddress(approval.to, approvedToken) || BigInt(approval.value) !== 0n || amount === null) throw Error("The token approval does not match this action.");
    const decoded = decodeFunctionData({ abi: erc20Abi, data: approval.data as `0x${string}` });
    if (decoded.functionName !== "approve") throw Error("Unexpected transaction before the wallet action.");
    const [spender, value] = decoded.args;
    const bound = amount / scale;
    if (!sameAddress(spender, final.to) || (value !== bound && !(value === 0n && index === 0 && approvals.length === 2))) throw Error("Approval must authorize only this action's exact token amount and contract.");
  }
}

export function AgentWalletActions({ agent, owned, api, live, send, changed, initialTarget, initialAsset, initialAction }: {
  agent: RuntimeAgent; owned: RuntimeAgent[]; api: AccountAPI; live: boolean;
  send: (sender: string, transactions: EvmTransaction[]) => Promise<string>; changed: () => Promise<void>;
  initialTarget?:string; initialAsset?:string; initialAction?:Action;
}) {
  const [action, setAction] = useState<Action>(initialAction||"deploy_token");
  const [assets, setAssets] = useState<BackingAsset[]>([]), [token, setToken] = useState<TokenSystem | null>(null), [payments, setPayments] = useState<PaymentSystem | null>(null);
  const [jobs, setJobs] = useState<(Job | PublicJob)[]>([]), [bounties, setBounties] = useState<Bounty[]>([]), [targets, setTargets] = useState<{ id: string; name: string; status: string }[]>(owned);
  const [ready, setReady] = useState(false), [globalPending, setGlobalPending] = useState(false), [pending, setPending] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [intent, setIntent] = useState<WalletActionIntent | null>(null), [hash, setHash] = useState(""), [uncertain, setUncertain] = useState(false);
  const [amount, setAmount] = useState("1"), [target, setTarget] = useState(initialTarget||agent.id), [assetAddress, setAssetAddress] = useState(initialAsset||USDT_ADDRESS), [all, setAll] = useState(false);
  const [name, setName] = useState(""), [symbol, setSymbol] = useState(""), [metadata, setMetadata] = useState(""), [pairAddress, setPairAddress] = useState("");
  const [bountyTitle,setBountyTitle]=useState(""),[bountyDescription,setBountyDescription]=useState(""),[bountyBudget,setBountyBudget]=useState("1"),[bountyDeadline,setBountyDeadline]=useState(""),[bountyPublic,setBountyPublic]=useState(true);
  const [jobId, setJobId] = useState(""), [bountyId, setBountyId] = useState(""), [days, setDays] = useState("1"), [side, setSide] = useState(true), [closes, setCloses] = useState("");
  const [signer, setSigner] = useState(agent.wallet || ""), [nonce, setNonce] = useState(""), [hours, setHours] = useState("24"), [perCall, setPerCall] = useState(String(agent.max_call)), [daily, setDaily] = useState(String(agent.daily_cap));
  const [tools, setTools] = useState<string[]>(agent.tools), [recipients, setRecipients] = useState<string[]>([]), [recipient, setRecipient] = useState(""), [tool, setTool] = useState(agent.tools[0] || ""), [requestHash, setRequestHash] = useState(""), [receiptHash, setReceiptHash] = useState(""), [pause, setPause] = useState(agent.status !== "paused");
  const storageKey = `tab:wallet:pending:${agent.id}`;
  const refresh = useCallback(async () => {
    const list = await api<WalletActionIntent[]>(`/account/runtime/${agent.id}/wallet-actions`);
    const local = saved(storageKey), next = list.find(i => !credits(i.action)) || local?.intent || null;
    let creditLocal = false; try { creditLocal = !!localStorage.getItem(`tab:credit:pending:${agent.id}`); } catch {}
    setGlobalPending(list.length > 0 || !!local || creditLocal); setReady(true); setIntent(next);
    if (next) { setHash(next.tx_hash || (local?.intent.id === next.id ? local.hash : "")); setUncertain(!!next.tx_hash || (local?.intent.id === next.id && local.uncertain)); }
    else { setHash(""); setUncertain(false); }
  }, [api, agent.id, storageKey]);
  useEffect(() => {
    if (!live) return;
    let alive = true;
    void refresh().catch(e => { if (alive) { setReady(false); setError(e.message); } });
    const resources = [api<BackingAsset[]>("/backing/assets").then(v => { if (alive) setAssets(v); }), api<TokenSystem>("/token/system").then(v => { if (alive) setToken(v); }), api<PaymentSystem>("/x402/system").then(v => { if (alive) setPayments(v); }), Promise.all([api<Job[]>(`/account/jobs?agent_id=${encodeURIComponent(agent.id)}`), api<PublicJob[]>("/jobs")]).then(([privateJobs, publicJobs]) => { if (alive) setJobs([...new Map([...publicJobs, ...privateJobs].map(j => [j.id, j])).values()]); }), Promise.all([api<Bounty[]>("/account/bounties"), api<Bounty[]>("/bounties")]).then(([privateBounties, publicBounties]) => { if (alive) setBounties([...new Map([...publicBounties, ...privateBounties].map(b => [b.id, b])).values()]); }), api<{ id: string; name: string; status: string }[]>("/agents/live").then(v => { if (alive) setTargets([...new Map([...v, ...owned].map(a => [a.id, a])).values()]); })];
    void Promise.allSettled(resources).then(results => { if (alive && results.some(r => r.status === "rejected")) setError("Some wallet data could not be loaded. Refresh before choosing an affected action."); });
    const listener = () => { void refresh().catch(e => { setReady(false); setError(e.message); }); };
    window.addEventListener("tab:wallet-actions-changed", listener);
    return () => { alive = false; window.removeEventListener("tab:wallet-actions-changed", listener); };
  }, [live, api, agent.id, owned, refresh]);
  async function act(fn: () => Promise<void>) { setPending(true); setError(""); setNotice(""); try { await fn(); } catch (e) { setError((e as Error).message); } finally { setPending(false); } }
  const chosenJob = jobs.find(j => j.id === jobId), chosenAsset = assets.find(a => sameAddress(a.address, assetAddress));
  const isBacking = ["back", "withdraw_backing", "back_bnb", "withdraw_bnb"].includes(action), isWithdrawal = ["withdraw_backing", "withdraw_bnb"].includes(action);
  const requiresTab = officialActions.has(action), tabReady = token?.status === "verified" && !!token.official_tab_address;
  const usable = live && !!agent.wallet && !!agent.registry_id && (agent.status === "ready" || recoveryActions.has(action)) && ready && !globalPending && !pending && (!requiresTab || tabReady);
  const allowedJobs = jobs.filter(j => j.funding === "funded" && (["bet_outcome", "resolve_outcome", "claim_outcome"].includes(action) || j.executor_id === agent.id));
  const merchants = [...new Map((payments?.merchants || []).map(m => [m.recipient.toLowerCase(), m])).values()];
  async function approvalContext(next: WalletActionIntent) {
    if (["back", "withdraw_backing"].includes(next.action)) { const asset = assets.find(a => sameAddress(a.address, String(next.details.token_address))); return { token: asset?.address, decimals: asset?.decimals ?? 18 }; }
    if (next.action === "stake" || next.action === "bond_job") {
      const address = next.action === "stake" ? token?.official_tab_address : jobs.find(j => j.id === next.details.job_id)?.bond_token_address;
      if (!address) throw Error("The token for this action is unavailable.");
      const metadata = await api<{chain_id:number;address:string;decimals:number}>(`/bnb/tokens/${address}`);
      if (metadata.chain_id !== BNB_CHAIN_ID || !sameAddress(metadata.address,address) || !Number.isInteger(metadata.decimals) || metadata.decimals<0 || metadata.decimals>18) throw Error("The token precision could not be verified on BNB Chain.");
      return {token:address,decimals:metadata.decimals};
    }
    return { token: USDT_ADDRESS, decimals: 18 };
  }
  function body(): Record<string, unknown> {
    const input: Record<string, unknown> = { action, amount: "0" };
    if (amountActions.has(action)) { exactAmount(isWithdrawal && all ? "0" : amount, action === "back" || action === "withdraw_backing" ? chosenAsset?.decimals : 18, isWithdrawal && all); input.amount = isWithdrawal && all ? "0" : amount; }
    if (isBacking) { input.target_agent_id = target; if (["back", "withdraw_backing"].includes(action)) { if (!chosenAsset?.enabled || chosenAsset.chain_id !== BNB_CHAIN_ID) throw Error("Choose a verified backing asset on BNB Chain."); input.token_address = chosenAsset.address; } }
    if (action === "deploy_token" || action === "pair_token") { if (!metadata.trim()) throw Error("Describe the token or provide its public metadata URL."); input.metadata_hash = keccak256(stringToHex(metadata.trim())); if (action === "deploy_token") { if (name.trim().length < 2 || name.trim().length > 48 || !/^[a-zA-Z0-9]{1,10}$/.test(symbol.trim())) throw Error("Use a token name from 2 to 48 characters and a symbol from 1 to 10 letters or digits."); input.name = name.trim(); input.symbol = symbol.trim(); } else { if (!isAddress(pairAddress, { strict: false })) throw Error("Enter the existing token's BNB contract address."); input.token_address = pairAddress.toLowerCase(); } }
    if (action === "stake") { if (!/^\d+$/.test(days) || Number(days) < 1 || Number(days) > 31) throw Error("Choose a lock from 1 to 31 days."); input.lock_seconds = Number(days) * 86400; input.token_address = token!.official_tab_address; }
    if (action === "pause_agent") input.paused = pause;
    if (jobActions.has(action)) { if (!chosenJob || !allowedJobs.some(j => j.id === chosenJob.id)) throw Error("Choose an eligible funded job."); input.job_id = chosenJob.id; if (action === "bond_job") { if (!chosenJob.bond_token_address || usdtUnits(String(chosenJob.bond_tokens)) === 0n) throw Error("This job has no published token bond."); input.amount = chosenJob.bond_tokens; input.penalty_bps = chosenJob.penalty_bps ?? 10000; } if (action === "open_outcome") { const end = Math.floor(new Date(closes).getTime() / 1000); if (!Number.isFinite(end) || end <= Date.now() / 1000 || end + 60 > new Date(chosenJob.deadline).getTime() / 1000) throw Error("Close positions at least one minute before the job deadline."); input.closes_at = end; } if (action === "bet_outcome") input.side = side; }
    if (action === "fund_bounty" || action === "claim_bounty") { const bounty = bounties.find(b => b.id === bountyId); if (!bounty || (action === "fund_bounty" ? bounty.funding !== "unfunded" : bounty.funding !== "funded" || !!bounty.assigned_agent_id)) throw Error("Choose an eligible bounty."); input.bounty_id = bounty.id; if (action === "fund_bounty") input.amount = bounty.budget; }
    if (["grant_session", "revoke_session", "session_pay"].includes(action)) { if (nonce && !validNonce(nonce)) throw Error("Use the exact unsigned 64-bit session nonce."); if (action !== "grant_session" && !validNonce(nonce)) throw Error("Enter the nonce from the original permission receipt."); if (nonce) input.session_nonce = nonce; }
    if (action === "grant_session") { const total = exactAmount(amount), per = exactAmount(perCall), cap = exactAmount(daily); if (per > exactAmount(String(agent.max_call)) || cap > exactAmount(String(agent.daily_cap)) || per > cap || cap > total || total > cap * 7n) throw Error("Keep per-call, daily, and total permission limits within the agent policy; total must cover the daily cap."); if (!isAddress(signer, { strict: false }) || !/^\d+$/.test(hours) || Number(hours) < 1 || Number(hours) > 168 || !tools.length || !recipients.length) throw Error("Choose a signer, approved tools and recipients, and an expiry from 1 to 168 hours."); Object.assign(input, { session_signer: signer.toLowerCase(), session_expires_at: Math.floor(Date.now() / 1000) + Number(hours) * 3600, per_call: perCall, daily_cap: daily, tools, recipients }); }
    if (action === "session_pay") { if (!merchants.some(m => sameAddress(m.recipient, recipient)) || !agent.tools.includes(tool) || !validHash(requestHash) || !validHash(receiptHash)) throw Error("Choose an approved recipient and tool, with nonzero 32-byte request and receipt commitments."); if (exactAmount(amount) > exactAmount(String(agent.max_call))) throw Error("Payment exceeds this agent's per-call limit."); Object.assign(input, { recipient: recipient.toLowerCase(), tool, request_hash: requestHash, receipt_hash: receiptHash }); }
    return input;
  }
  async function createBounty() { const budget=exactAmount(bountyBudget); const deadline=new Date(bountyDeadline); if(budget>exactAmount(String(agent.daily_cap))||bountyTitle.trim().length<3||bountyDescription.trim().length<5||!Number.isFinite(deadline.getTime())||deadline.getTime()<Date.now()+300000||deadline.getTime()>Date.now()+30*86400000) throw Error("Use a title, description, budget within this agent's daily cap, and a deadline from five minutes to thirty days away."); const draft=await api<Bounty>("/account/bounties",{method:"POST",body:JSON.stringify({title:bountyTitle.trim(),description:bountyDescription.trim(),budget:bountyBudget,deadline:deadline.toISOString(),tools:agent.tools,public_activity:bountyPublic})});setBounties(v=>[draft,...v]);setBountyId(draft.id);setNotice("Bounty draft saved. Review its funding transaction when ready."); }
  async function prepare() { if (!usable) throw Error("Resolve pending actions and verify the wallet data before preparing another action."); const input = body(); const next = await api<WalletActionIntent>(`/account/runtime/${agent.id}/wallet-actions/prepare`, { method: "POST", body: JSON.stringify(input) }); const context = await approvalContext(next); validateWalletActionIntent(next, agent, context.token, context.decimals, input); setIntent(next); setGlobalPending(true); setHash(""); setUncertain(false); changedEvent(); }
  async function confirm(value: string) { if (!intent) return; await recordSubmitted(api, `/account/wallet-actions/${intent.id}/submitted`, value); const result = await api<{ status: string }>(`/account/wallet-actions/${intent.id}/confirm`, { method: "POST", body: JSON.stringify({ tx_hash: value }) }); if (result.status !== "confirmed") throw Error("The wallet action is not confirmed yet."); remember(storageKey, null); setIntent(null); setHash(""); setUncertain(false); setNotice("Wallet action confirmed on BNB Chain."); changedEvent(); await Promise.all([refresh(), changed()]); }
  const amountLabel = action === "deploy_token" ? "fixed token supply" : action === "stake" ? "amount in TAB" : action.includes("bnb") ? "amount in BNB" : action === "back" || action === "withdraw_backing" ? `amount in ${chosenAsset?.symbol || "tokens"}` : action === "grant_session" ? "total authorized USDT" : "amount in USDT";
  return <div className="paid-tool" data-testid="agent-wallet-actions"><h3>wallet tools</h3><p>Create or pair an agent token, manage backing, and set onchain payment permissions. Each action needs a wallet review and BNB for fees.</p>
    {!live || !agent.registry_id ? <p className="muted">Register this agent with the verified BNB contracts to use wallet tools.</p> : <>
      <form className="policy-fields" onSubmit={e => { e.preventDefault(); void act(prepare); }}>
        <label>wallet action<select aria-label="wallet action" value={action} disabled={pending || !!intent} onChange={e => { setAction(e.target.value as Action); setError(""); setAll(false); }}>{[...new Set(actionKeys.map(key => actions[key][0]))].map(group => <optgroup label={group} key={group}>{actionKeys.filter(key => actions[key][0] === group).map(key => <option value={key} key={key}>{actions[key][1]}</option>)}</optgroup>)}</select></label>
        {requiresTab && !tabReady && <p className="field-help">{token ? "This action requires the official TAB token. Its contract is not verified yet." : "Checking the official TAB token…"}</p>}
        {agent.status === "paused" && !recoveryActions.has(action) && <p className="field-help">Resume this agent before creating a new onchain commitment.</p>}
        {(action === "deploy_token" || action === "pair_token") && <>{action === "deploy_token" ? <><label>token name<input value={name} onChange={e => setName(e.target.value)} maxLength={48} /></label><label>token symbol<input value={symbol} onChange={e => setSymbol(e.target.value)} maxLength={10} /></label><p className="field-help">The factory creates a fixed supply for this wallet. It has no later mint, pause, or transfer-tax controls. Creating a token does not create a trading pool.</p></> : <label>existing token contract<input value={pairAddress} onChange={e => setPairAddress(e.target.value)} placeholder="0x…" spellCheck={false} /></label>}<label>public token description or metadata URL<textarea value={metadata} onChange={e => setMetadata(e.target.value)} maxLength={4000} /></label><p className="field-help">A hash of this text is recorded with the token pairing. Keep the original metadata available to others.</p></>}
        {isBacking && <><label>backing target<select aria-label="backing target" value={target} onChange={e => setTarget(e.target.value)}>{targets.filter(t => ["ready", "paused"].includes(t.status)).map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{(action === "back" || action === "withdraw_backing") && <label>backing token<select aria-label="backing token" value={assetAddress.toLowerCase()} onChange={e => setAssetAddress(e.target.value)}>{assets.filter(a => a.address).map(a => <option key={a.address!} value={a.address!.toLowerCase()} disabled={!a.enabled}>{a.symbol} · {a.name}</option>)}</select></label>}<p className="field-help">Backing stays in contract custody for this agent and your wallet can withdraw its recorded deposit. It does not guarantee credit repayment. Tokenized stocks are issuer tokens; no stock trading route is provided here.</p>{isWithdrawal && <label className="checkbox-row"><input type="checkbox" checked={all} onChange={e => setAll(e.target.checked)} />withdraw my entire recorded backing</label>}</>}
        {amountActions.has(action) && !all && <label>{amountLabel}<input inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} /></label>}
        {action === "stake" && <label>lock duration in days<input inputMode="numeric" value={days} onChange={e => setDays(e.target.value)} /></label>}
        {action === "unstake" && <p className="field-help">Withdraws the recorded TAB stake after its lock ends. The contract checks the unlock time.</p>}
        {action === "pause_agent" && <><label>onchain spending<select value={String(pause)} onChange={e => setPause(e.target.value === "true")}><option value="true">pause new spending</option><option value="false">resume spending</option></select></label><p className="field-help">This changes the registered agent's spending permission. It also updates its app status after confirmation.</p></>}
        {jobActions.has(action) && <><label>funded job<select aria-label="funded job" value={jobId} onChange={e => setJobId(e.target.value)}><option value="">choose a funded job</option>{allowedJobs.map(j => <option key={j.id} value={j.id}>{j.title} · {j.state}</option>)}</select></label>{allowedJobs.length === 0 && <p className="field-help">No eligible funded jobs are available for this action.</p>}{action === "bind_job_agent" && <p className="field-help">The assigned wallet binds this exact registered agent before provider payments, a token bond, or an outcome pool.</p>}{action === "bond_job" && chosenJob && <p className="field-help">Published bond: {chosenJob.bond_tokens} tokens. Deadline penalty: {(chosenJob.penalty_bps ?? 10000) / 100}%. Bind this agent to the job first. Buyer disagreement alone cannot slash the bond.</p>}{action === "open_outcome" && <label>positions close at<input type="datetime-local" value={closes} onChange={e => setCloses(e.target.value)} /></label>}{action === "bet_outcome" && <label>position<select value={String(side)} onChange={e => setSide(e.target.value === "true")}><option value="true">for timely submission</option><option value="false">against timely submission</option></select></label>}{action.includes("outcome") && <p className="field-help">Outcomes use the onchain submission deadline. A position can lose its full USDT amount. Resolution and claims depend on the recorded job state.</p>}</>}
        {(action === "fund_bounty" || action === "claim_bounty") && <><label>bounty<select aria-label="bounty" value={bountyId} onChange={e => setBountyId(e.target.value)}><option value="">choose a bounty</option>{bounties.filter(b => action === "fund_bounty" ? b.funding === "unfunded" : b.funding === "funded" && !b.assigned_agent_id).map(b => <option key={b.id} value={b.id}>{b.title} · {b.budget} USDT</option>)}</select></label><p className="field-help">Funding transfers the draft's exact USDT budget into escrow. Claiming requires holding official TAB and this agent's paired token.</p></>}
        {action === "fund_bounty" && <details><summary>create a bounty draft</summary><label>bounty title<input value={bountyTitle} maxLength={120} onChange={e=>setBountyTitle(e.target.value)} /></label><label>bounty description<textarea value={bountyDescription} maxLength={1200} onChange={e=>setBountyDescription(e.target.value)} /></label><label>bounty budget in USDT<input inputMode="decimal" value={bountyBudget} onChange={e=>setBountyBudget(e.target.value)} /></label><label>bounty deadline<input type="datetime-local" value={bountyDeadline} onChange={e=>setBountyDeadline(e.target.value)} /></label><label className="checkbox-row"><input type="checkbox" checked={bountyPublic} onChange={e=>setBountyPublic(e.target.checked)} />show this bounty publicly</label><p className="field-help">Uses this agent's approved tools: {agent.tools.join(", ")}. Saving a draft transfers no funds.</p><button type="button" className="outline" disabled={pending} onClick={()=>act(createBounty)}>save bounty draft</button></details>}
        {["grant_session", "revoke_session", "session_pay"].includes(action) && <label>session nonce{action === "grant_session" ? " (optional)" : ""}<input inputMode="numeric" value={nonce} onChange={e => setNonce(e.target.value)} placeholder={action === "grant_session" ? "generated when prepared" : "from the permission receipt"} /></label>}
        {action === "grant_session" && <><label>authorized signer<input value={signer} onChange={e => setSigner(e.target.value)} spellCheck={false} /></label><label>USDT per call<input inputMode="decimal" value={perCall} onChange={e => setPerCall(e.target.value)} /></label><label>USDT per day<input inputMode="decimal" value={daily} onChange={e => setDaily(e.target.value)} /></label><label>expires in hours<input inputMode="numeric" value={hours} onChange={e => setHours(e.target.value)} /></label><fieldset><legend>allowed tools</legend>{agent.tools.map(t => <label className="checkbox-row" key={t}><input type="checkbox" checked={tools.includes(t)} onChange={e => setTools(v => e.target.checked ? [...v, t] : v.filter(x => x !== t))} />{t}</label>)}</fieldset><fieldset><legend>allowed merchant recipients</legend>{merchants.map(m => <label className="checkbox-row" key={m.recipient}><input type="checkbox" checked={recipients.includes(m.recipient)} onChange={e => setRecipients(v => e.target.checked ? [...v, m.recipient] : v.filter(x => x !== m.recipient))} /><span>{m.id}<small className="wallet-address">{m.recipient}</small></span></label>)}</fieldset><p className="field-help">Permission does not deposit funds. Fund USDT spending separately. Keep the prepared session nonce to revoke the permission later.</p></>}
        {action === "session_pay" && <><label>approved merchant<select value={recipient} onChange={e => setRecipient(e.target.value)}><option value="">choose a recipient</option>{merchants.map(m => <option key={m.recipient} value={m.recipient}>{m.id}</option>)}</select></label><label>payment tool<select value={tool} onChange={e => setTool(e.target.value)}>{agent.tools.map(t => <option key={t}>{t}</option>)}</select></label><label>request commitment<input value={requestHash} onChange={e => setRequestHash(e.target.value)} placeholder="0x… (32 bytes)" /></label><label>receipt commitment<input value={receiptHash} onChange={e => setReceiptHash(e.target.value)} placeholder="0x… (32 bytes)" /></label><p className="field-help">Advanced merchant payment from deposited USDT. This wallet must be the session's signer. These commitments record the payment; this action does not retrieve an x402 response or prove provider delivery.</p></>}
        {(action === "grant_session" || action === "session_pay") && !merchants.length && <p className="field-help">No merchant recipients are connected. A recipient must be approved before this action can be prepared.</p>}
        <button className="outline" disabled={!usable || (["grant_session", "session_pay"].includes(action) && !merchants.length)}>review wallet action</button>
      </form>
      {globalPending && !intent && <p className="field-help">Another wallet action is pending. Resolve it in its credit or finance panel before preparing another action.</p>}
      <button className="text-link" disabled={pending} onClick={() => act(refresh)}>refresh pending actions</button>
      {intent && <div className="payment-quote"><h4>review {actions[intent.action as Action]?.[1] || intent.action.replaceAll("_", " ")}</h4><p>BNB Smart Chain · wallet <span className="wallet-address">{intent.sender}</span></p>{typeof intent.details.amount === "string" && <p>exact amount: {intent.details.amount}{intent.action.includes("bnb") ? " BNB" : ""}</p>}<p>{intent.transactions.length} wallet transaction{intent.transactions.length === 1 ? "" : "s"}. Token approvals are limited to this action.</p><p className="wallet-address">action contract {intent.to}</p><details><summary>review all terms</summary><pre className="run-output">{JSON.stringify(intent.details, null, 2)}</pre></details>
        {!hash && !uncertain && <button className="primary" disabled={pending || Date.parse(intent.expires_at) <= Date.now()} onClick={() => act(async () => { const context = await approvalContext(intent); validateWalletActionIntent(intent, agent, context.token, context.decimals); remember(storageKey, { intent, hash: "", uncertain: true }); setUncertain(true); changedEvent(); let sent: string; try { sent = await send(intent.sender, intent.transactions); } catch (error) { if (walletPromptRejected(error)) { remember(storageKey,null); setUncertain(false); changedEvent(); } throw error; } setHash(sent); remember(storageKey, { intent, hash: sent, uncertain: true }); changedEvent(); await recordSubmitted(api, `/account/wallet-actions/${intent.id}/submitted`, sent); await waitForTransaction(sent); await confirm(sent); })}>confirm wallet action</button>}
        {uncertain && !hash && <p className="field-help">The wallet interaction may have submitted a transaction. Check your wallet activity and paste the final action hash before preparing another action. The preparation expiry does not prove whether a transaction was broadcast.</p>}
        <label>submitted action hash<input value={hash} onChange={e => setHash(e.target.value)} placeholder="0x…" spellCheck={false} /></label><button className="outline" disabled={pending || !/^0x[0-9a-fA-F]{64}$/.test(hash)} onClick={() => act(() => confirm(hash))}>verify wallet action</button>{hash && <><button className="outline" disabled={pending} onClick={() => act(async () => { await recordSubmitted(api, `/account/wallet-actions/${intent.id}/submitted`, hash); await api(`/account/wallet-actions/${intent.id}/release-failed`, { method: "POST" }); remember(storageKey, null); setIntent(null); setHash(""); setUncertain(false); setNotice("Reverted transaction verified. A new action can be reviewed."); changedEvent(); await refresh(); })}>check reverted action</button><a href={explorer(hash)} target="_blank" rel="noreferrer">view transaction ↗</a></>}
      </div>}
    </>}
    {notice && <p role="status">{notice}</p>}{error && <p role="alert" className="form-error">{error}</p>}
  </div>;
}
