import { useHolderGate } from "../lib/holder-access";
import { useCallback, useEffect, useState } from "react";
import type { RuntimeAgent } from "../lib/api";
import type { AccountAPI } from "../lib/jobs";
import { amountFromUnits } from "../lib/amounts";
import { explorer, waitForTransaction, type EvmTransaction } from "../lib/evm";
import { validatePaymentQuote, type Merchant, type PaymentDelivery, type PaymentHistory, type PaymentQuote, type PaymentSystem } from "../lib/payments";

function pendingPayment(key:string){try{return sessionStorage.getItem(key)||"";}catch{return "";}}
function rememberPayment(key:string,id:string){try{if(id)sessionStorage.setItem(key,id);else sessionStorage.removeItem(key);}catch{ /* Server history remains the source for submitted payment recovery. */ }}

function delivered(item: PaymentHistory) {
  return item.status === "confirmed" && item.delivery?.status === "completed" && item.delivery.settled_usdt === true && item.delivery.quote_id === item.quote_id && item.delivery.provider === item.provider && item.delivery.data != null;
}
function deliveryText(data: unknown) { return typeof data === "string" ? data : JSON.stringify(data, null, 2); }
function downloadDelivery(delivery: PaymentDelivery) {
  const url = URL.createObjectURL(new Blob([deliveryText(delivery.data)], { type: typeof delivery.data === "string" ? "text/plain" : "application/json" }));
  const link = document.createElement("a"); link.href = url; link.download = `tab-paid-result-${delivery.quote_id}.${typeof delivery.data === "string" ? "txt" : "json"}`; link.click(); URL.revokeObjectURL(url);
}

export function AgentPayments({agent, api, live, send, sign, changed}: {agent:RuntimeAgent;api:AccountAPI;live:boolean;send:(sender:string,transactions:EvmTransaction[])=>Promise<string>;sign:(quote:PaymentQuote,merchant:Merchant)=>Promise<string>;changed:()=>Promise<void>}) {
  const access = useHolderGate();
  const [system,setSystem]=useState<PaymentSystem|null>(null),[merchantId,setMerchantId]=useState(""),[quote,setQuote]=useState<PaymentQuote|null>(null),[history,setHistory]=useState<PaymentHistory[]>([]),[pending,setPending]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[reconcileHash,setReconcileHash]=useState("");
  const storageKey=`tab:x402:pending:${agent.id}`;
  const [uncertain,setUncertain]=useState<string>(()=>pendingPayment(storageKey)||"");
  const refresh=useCallback(async()=>{const [s,h]=await Promise.all([api<PaymentSystem>("/x402/system"),api<PaymentHistory[]>(`/account/runtime/${agent.id}/x402`)]);setSystem(s);setHistory(h);const unresolved=h.find(p=>["submitted","uncertain"].includes(p.status));if(unresolved){setUncertain(unresolved.quote_id);setReconcileHash(unresolved.tx_hash||"");}else setUncertain(current=>{if(h.some(p=>p.quote_id===current&&["confirmed","cancelled"].includes(p.status))){rememberPayment(storageKey,"");return "";}return current;});},[api,agent.id,storageKey]);
  useEffect(()=>{void refresh().catch(e=>setError(e.message));},[refresh]);
  async function act(action:()=>Promise<void>){setPending(true);setError("");setNotice("");try{await action();}catch(e){setError((e as Error).message);}finally{setPending(false);}}
  const merchant=system?.merchants.find(m=>m.id===merchantId);
  const enabled=access.allows("x402")&&live&&system?.settlement_enabled===true&&agent.status==="ready"&&agent.tools.includes("x402");
  return <div className="paid-tool" data-testid="agent-payments">
    <h3><span className="x402-accent">x402</span> requests</h3>
    <p>Choose an approved tool, review its exact USDT price, then authorize one request. Wallet approvals use BNB for fees.</p>
    {!live?<p className="muted">Payments open when the BNB Chain contracts are verified.</p>:!agent.tools.includes("x402")?<p className="muted">Enable x402 in this agent's tool settings to request a payment.</p>:!system?<p className="muted">{error?"Payment provider status is unavailable.":"Checking payment providers…"}</p>:!system.merchants.length?<p className="muted">No USDT payment providers are connected yet.</p>:<>
      <label>provider<select aria-label="payment provider" value={merchantId} disabled={pending||!!uncertain} onChange={e=>{setMerchantId(e.target.value);setQuote(null);}}><option value="">choose a provider</option>{system.merchants.map(m=><option key={m.id} value={m.id} disabled={m.capability_status!=="quote_ready"||!m.settlement_enabled}>{m.id}{m.capability_status!=="quote_ready"||!m.settlement_enabled?" · unavailable":""}</option>)}</select></label>
      <button className="outline" disabled={!enabled||pending||!merchant||merchant.capability_status!=="quote_ready"||!merchant.settlement_enabled||!!uncertain} onClick={()=>act(async()=>{await access.require("x402");const next=await api<PaymentQuote>(`/account/runtime/${agent.id}/x402/quote`,{method:"POST",body:JSON.stringify({merchant_id:merchantId})});validatePaymentQuote(next,merchant!,agent.wallet!,String(agent.max_call),String(agent.daily_cap));setQuote(next);})}>request price</button>
      {quote&&merchant&&<div className="payment-quote"><strong>{amountFromUnits(BigInt(quote.offer.amount_units))} USDT</strong><p>{quote.offer.resource.description||merchant.id}</p><p className="field-help">recipient <span className="wallet-address">{merchant.recipient}</span></p>
        {quote.status==="approval_required"?<><p>This wallet needs an approval for exactly this amount. A fresh price is required after approval.</p><button className="primary" disabled={pending||!!uncertain||!access.allows("x402")} onClick={()=>act(async()=>{await access.require("x402");validatePaymentQuote(quote,merchant,agent.wallet!,String(agent.max_call),String(agent.daily_cap));const hash=await send(quote.sender,quote.transactions!);setQuote(null);setNotice(`Approval submitted: ${hash}. Checking confirmation.`);await waitForTransaction(hash);setNotice("USDT approval confirmed. Request a fresh price.");})}>approve {amountFromUnits(BigInt(quote.offer.amount_units))} USDT</button></>:<><p className="field-help">One authorization, expiring {new Date((quote.expires_at||0)*1000).toLocaleTimeString()}.</p><button className="primary" disabled={pending||!!uncertain||!access.allows("x402")} onClick={()=>act(async()=>{await access.require("x402");const signature=await sign(quote,merchant);const id=quote.quote_id!;rememberPayment(storageKey,id);setUncertain(id);const result=await api<{payment:PaymentHistory;result:string;service_status:string}>(`/account/runtime/${agent.id}/x402/${id}/execute`,{method:"POST",body:JSON.stringify({signature})});if(result.payment.status!=="confirmed")throw Error("The payment is not confirmed. Reconcile its transaction before another request.");rememberPayment(storageKey,"");setUncertain("");setQuote(null);setNotice(result.service_status==="failed_after_payment"?"Payment confirmed, but the provider request failed. Check the receipt and contact the provider before paying again.":`Payment confirmed. ${result.result}`);await Promise.all([refresh(),changed()]);})}>authorize & request</button></>}
      </div>}
    </>}
    {uncertain&&<div className="payment-quote"><strong>check the submitted payment</strong><p>This request may have settled. Verify its transaction before requesting another payment.</p><label>BNB Chain transaction hash<input value={reconcileHash} onChange={e=>setReconcileHash(e.target.value)} placeholder="0x…" spellCheck={false}/></label><button className="outline" disabled={pending||!/^0x[0-9a-fA-F]{64}$/.test(reconcileHash)} onClick={()=>act(async()=>{const result=await api<PaymentHistory>(`/account/runtime/${agent.id}/x402/${uncertain}/reconcile`,{method:"POST",body:JSON.stringify({tx_hash:reconcileHash})});if(result.status!=="confirmed")throw Error(`Transaction ${result.status}. Keep this payment pending until its outcome is verified.`);rememberPayment(storageKey,"");setUncertain("");setQuote(null);setNotice("Payment confirmed from its onchain receipt.");await Promise.all([refresh(),changed()]);})}>verify payment</button>{!reconcileHash&&<button className="outline" disabled={pending} onClick={()=>act(async()=>{await api(`/account/runtime/${agent.id}/x402/${uncertain}/release-expired`,{method:"POST"});await refresh();setNotice("Expired authorization checked onchain. Only an unused authorization can be released.");})}>check expired payment</button>}</div>}
    {notice&&<p role="status" className="field-help">{notice}</p>}{error&&<p role="alert" className="form-error">{error}</p>}
    {history.length>0&&<section className="payment-deliveries" aria-label="Paid request results"><h4>paid requests and results</h4>{history.map(item=>{
      const available = delivered(item);
      return <article className="payment-delivery" key={item.quote_id} data-delivery-status={available?"completed":item.delivery?.status||"unavailable"}>
        <p>{item.provider} · {item.amount} USDT · payment {item.status}{item.tx_hash&&<a href={explorer(item.tx_hash)} target="_blank" rel="noreferrer"> transaction ↗</a>}</p>
        {available&&item.delivery?<><details open><summary>delivered result</summary><pre className="payment-delivery-data">{deliveryText(item.delivery.data)}</pre><div className="payment-delivery-actions"><button className="text-link" onClick={()=>downloadDelivery(item.delivery!)}>download result</button>{item.delivery.received_at&&<time dateTime={item.delivery.received_at}>{new Date(item.delivery.received_at).toLocaleString()}</time>}</div><details><summary>delivery receipt</summary><p className="field-help">resource {item.delivery.resource_url}</p>{item.delivery.response_hash&&<p className="field-help wallet-address">response hash {item.delivery.response_hash}</p>}</details></details><button className="outline" disabled={pending||!!uncertain||!live||agent.status!=="ready"||!access.allows("run")} onClick={()=>act(async()=>{await access.require("run",undefined,agent.wallet||undefined);await api(`/account/runtime/${agent.id}/run`,{method:"POST",body:JSON.stringify({quote_id:item.quote_id})});await Promise.all([refresh(),changed()]);setNotice("Agent run recorded. Check its result in the run receipt. Stored paid data is reused without purchasing it again.");})}>run with purchased data</button><p className="field-help">Reuses this saved result after checking the agent's current tool permissions. Model calls can use provider credits. Review when the data was received before using it.</p></>:<p className="field-help">{item.status!=="confirmed"?"Delivery becomes available after payment and the provider response are verified.":item.delivery?.status==="failed_after_payment"?"Payment confirmed, but the provider did not deliver a usable result. Do not pay again before checking the transaction and contacting the provider.":"Payment confirmed. No delivered response was saved for this request."}</p>}
      </article>;
    })}</section>}
  </div>;
}
