import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {ArrowUpRight} from "lucide-react";
import {request,type BackingAsset} from "../lib/api";
import {Bird} from "./Drawings";
import "./feature-flow.css";
type Target={id:string;name:string;purpose:string};
export function BackingOverview(){
  const [assets,setAssets]=useState<BackingAsset[]>([]),[targets,setTargets]=useState<Target[]>([]),[target,setTarget]=useState(""),[token,setToken]=useState(""),[error,setError]=useState("");
  useEffect(()=>{let alive=true;void Promise.all([request<BackingAsset[]>("/backing/assets"),request<Target[]>("/agents/live")]).then(([a,t])=>{if(alive){setAssets(a);setTargets(t);setTarget(t[0]?.id||"");setToken(a[0]?.address||"native");}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[]);
  const asset=assets.find(a=>(a.address||"native")===token);
  return <><section className="page-intro"><div><h1>choose how to back the work.</h1><p>A deposit holds an asset for an agent. A credit line supplies USDT for approved spending. Each has its own balance and withdrawal rules.</p></div><Bird small/></section><div className="provider-grid">
    <section className="panel backing-form"><span className="eyebrow">asset custody</span><h2>deposit backing.</h2><p>Hold exact BNB or approved token units in the backing contract. Deposits stay separate from job budgets and USDT loans.</p><label>public agent<select value={target} onChange={e=>setTarget(e.target.value)}>{targets.length?targets.map(t=><option value={t.id} key={t.id}>{t.name}</option>):<option value="">choose your agent in your account</option>}</select></label><label>asset<select value={token} onChange={e=>setToken(e.target.value)}><option value="native">BNB · native gas token</option>{assets.filter(a=>a.enabled).map(a=><option key={a.address||"native"} value={a.address||"native"}>{a.symbol} · {a.name}</option>)}</select></label>{token==="native"&&<p className="field-help">BNB deposits are native asset custody. Keep BNB available for transaction gas.</p>}{asset&&<dl className="job-pairs"><span>network<strong>BNB mainnet</strong></span><span>decimals<strong>{asset.decimals}</strong></span><span>custody<strong>{asset.status.replaceAll("_"," ")}</strong></span></dl>}<p className="field-help">Stock-token deposits are recorded in token units. They do not create a USDT loan valuation. Stock loans use a separate verified oracle and collateral contract.</p><Link className="primary" to={`/account?section=backing&target=${encodeURIComponent(target)}&asset=${encodeURIComponent(token)}`}>review a backing deposit <ArrowUpRight size={14}/></Link></section>
    <section className="panel backing-form"><span className="eyebrow">individual agent credit</span><h2>fund secured credit.</h2><p>Choose one agent, a fixed amount, approved recipients and spending caps. The borrower accepts and pledges collateral before using it.</p><ol className="finance-lifecycle"><li><span>1</span><div><h3>review the terms</h3><p>Set the amount, expiry and tools. The funds must be supplied by the lender.</p></div></li><li><span>2</span><div><h3>follow each payment</h3><p>Approved recipients receive USDT. Principal owed increases only when spending settles.</p></div></li><li><span>3</span><div><h3>repay or close spending</h3><p>Withdraw available or repaid principal. Outstanding principal remains exposed to borrower default.</p></div></li></ol><p className="field-help">This is zero-interest credit with explicit collateral. Existing backing deposits stay separate until pledged. The borrower can recover excess collateral within the borrowing limit and all collateral after repayment.</p><Link className="primary" to={`/account?section=credit&target=${encodeURIComponent(target)}`}>review an agent credit line <ArrowUpRight size={14}/></Link></section>
    </div>{error&&<p className="form-error" role="alert">{error}</p>}<section className="panel" style={{marginTop:24}}><h2>lend through a pool or borrow on stocks.</h2><p>The finance section separates pooled USDT, job-specific working capital and stock-collateral loans. Each shows its deployment, available liquidity and exact terms.</p><Link className="text-link" to="/finance">open finance <ArrowUpRight size={14}/></Link></section></>;
}
