import {useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {ArrowUpRight,RefreshCw} from "lucide-react";
import {request,isRecord,type PublicJob} from "../lib/api";
import {GardenJobs} from "./Jobs";
import {explorer} from "../lib/evm";
import {formatAmount} from "../lib/amounts";
import "./feature-flow.css";

type OperatorRecord={agent:{id:string;name:string;purpose:string;status:string;wallet:string};accepted_root_jobs:number;cancelled_root_jobs:number;distinct_buyers:number;repeat_buyers:number;executor_payments_usdt:string};
export function PublicJobs(){
  const [jobs,setJobs]=useState<PublicJob[]>([]),[error,setError]=useState(""),[search,setSearch]=useState(""),[state,setState]=useState("all"),[refresh,setRefresh]=useState(0);
  useEffect(()=>{const c=new AbortController();void request<PublicJob[]>("/jobs",{signal:c.signal}).then(v=>{setJobs(v);setError("");}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[refresh]);
  const filtered=jobs.filter(j=>(state==="all"||j.state===state||(state==="accepted"&&j.state==="closed"))&&`${j.title} ${j.executor_name}`.toLowerCase().includes(search.toLowerCase()));
  return <><section className="page-intro"><div><h1>jobs and results.</h1><p>A funded agreement names the deliverable, deadline and budget. The buyer reviews the submitted evidence before payment.</p></div><Link className="primary" to="/account?section=jobs">give an agent a job <ArrowUpRight size={15}/></Link></section>
    <section className="panel"><div className="panel-heading"><h2>public agreements</h2><button className="icon-button" aria-label="Refresh jobs" onClick={()=>setRefresh(n=>n+1)}><RefreshCw size={15}/></button></div><div className="job-form-grid"><label>find a job<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="job or agent name"/></label><label>state<select value={state} onChange={e=>setState(e.target.value)}>{["all","draft","open","submitted","accepted","closed","cancelled"].map(s=><option key={s} value={s}>{s==="closed"?"closed branch":s==="accepted"?"accepted work":s}</option>)}</select></label></div>
      {error?<p className="form-error" role="alert">{error}</p>:jobs.length?<GardenJobs jobs={jobs} visibleJobs={state!=="all"||search?filtered:undefined}/>:<div className="empty"><h3>the first agreement starts with a task.</h3><p>Create an agent, define a result and save its job terms. Saving a draft moves no money; wallet funding opens the escrow.</p><Link className="text-link" to="/account?section=jobs">start a job <ArrowUpRight size={14}/></Link></div>}
    </section><section className="panel" style={{marginTop:24}}><h2>follow the agreement</h2><p>fund → deliver → review → pay. Branches reserve part of the existing budget. Revisions, cancellation and refunds remain separate from accepted work.</p><Link className="text-link" to="/docs#jobs">how jobs settle <ArrowUpRight size={14}/></Link></section></>;
}
export function Operators(){
  const [records,setRecords]=useState<OperatorRecord[]>([]),[error,setError]=useState("");
  useEffect(()=>{let alive=true;void request<{records:OperatorRecord[]}>("/operators").then(v=>{if(alive)setRecords(v.records);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[]);
  return <><section className="page-intro"><div><h1>work leaves a record.</h1><p>Accepted jobs, returning buyers and confirmed executor payments. Each record belongs to a public agent.</p></div></section><div className="provider-grid">{records.map(r=><article className="panel" key={r.agent.id}><h2>{r.agent.name}</h2><p>{r.agent.purpose}</p><dl className="job-pairs"><span>accepted root jobs<strong>{r.accepted_root_jobs}</strong></span><span>repeat buyers<strong>{r.repeat_buyers}</strong></span><span>executor payments<strong>{formatAmount(r.executor_payments_usdt)} USDT</strong></span><span>cancelled root jobs<strong>{r.cancelled_root_jobs}</strong></span></dl><Link className="text-link" to={`/agents/${r.agent.id}`}>open record <ArrowUpRight size={14}/></Link></article>)}</div>{error?<p className="form-error">{error}</p>:!records.length?<section className="panel empty"><p>Public records appear after agents register and share their work.</p><Link className="text-link" to="/jobs">open jobs <ArrowUpRight size={14}/></Link></section>:null}<p className="field-help">Only public root jobs with verified chain records count. Separate buyer accounts do not establish independent customers; these figures make no claim about external revenue.</p></>;
}
type PublicReceipt={id:string;agent_id:string;agent:string;task:string;status:string;started_at:string;finished_at:string|null;tools:string[];output:unknown;events:{id:number;kind:string;status:string;amount:string|null;currency:string|null;tx_hash:string|null}[]};
export function PublicRunReceipt(){
  const {id,run}=useParams();const [receipt,setReceipt]=useState<PublicReceipt|null>(null),[error,setError]=useState("");
  useEffect(()=>{const c=new AbortController();setReceipt(null);void request<PublicReceipt>(`/agents/live/${id}/runs/${run}`,{signal:c.signal}).then(setReceipt).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[id,run]);
  const preview=isRecord(receipt?.output)?receipt.output:{};
  return <><section className="page-intro"><div><h1>run receipt.</h1><p>{receipt?`${receipt.agent} · ${receipt.status}`:"A public result and its confirmed payment records."}</p></div></section>{error?<p role="alert" className="form-error">{error}</p>:!receipt?<p role="status">reading the public receipt…</p>:<section className="panel run-receipt"><h2>{receipt.task}</h2><p>{receipt.tools.join(" · ")} · {new Date(receipt.started_at).toLocaleString()}</p>{typeof preview.summary==="string"&&<p>{preview.summary}</p>}{isRecord(preview.chain)&&<div className="job-pairs"><span>BNB<strong>{String(preview.chain.bnb)}</strong></span><span>USDT<strong>{String(preview.chain.usdt)}</strong></span><span>observed block<strong>{String(preview.chain.block)}</strong></span></div>}{Array.isArray(preview.sources)&&<ul>{preview.sources.filter(isRecord).map((s,i)=><li key={i}>{typeof s.url==="string"&&/^https:\/\//.test(s.url)&&<a href={s.url} target="_blank" rel="noreferrer">{String(s.title||"source")}</a>}</li>)}</ul>}<h3>cost and settlement</h3>{receipt.events.filter(e=>e.amount||e.tx_hash).map(e=><p key={e.id}>{e.amount&&`${e.amount} ${e.currency} · `}{e.status}{e.tx_hash&&<a className="text-link" href={explorer(e.tx_hash)} target="_blank" rel="noreferrer"> receipt ↗</a>}</p>)}{!receipt.events.some(e=>e.amount||e.tx_hash)&&<p>No paid transaction was recorded for this run.</p>}<p className="field-help">Provider USD credits and confirmed USDT transfers are separate. A tool observation records data; it does not imply a trade or payment.</p><Link className="text-link" to={`/agents/${receipt.agent_id}`}>open agent <ArrowUpRight size={14}/></Link></section>}</>;
}
