import { chromium } from "../node_modules/playwright/index.mjs";
import assert from "node:assert/strict";
const origin = process.env.TAB_TEST_ORIGIN ?? "http://127.0.0.1:5198";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const calls = [], errors = [];
let failRevoke = false, resolveGenerate;
page.on("pageerror", error => errors.push(error.message));
await page.route("**/api/account/runtime/*/key", async route => {
  const method = route.request().method(), path = new URL(route.request().url()).pathname;
  calls.push({ method, path });
  if (method === "DELETE") return route.fulfill(failRevoke ? { status: 503, json: { detail: "Key storage temporarily unavailable." } } : { status: 204 });
  if (resolveGenerate) await new Promise(resolve => { resolveGenerate = resolve; });
  return route.fulfill({ json: { key: "qa-only-token-no-auth" } });
});
await page.goto(`${origin}/tests/access-key.html`, { waitUntil: "networkidle" });
await page.locator("summary").click();
await page.getByRole("button", { name: "generate access key", exact: true }).click();
await page.getByRole("button", { name: "copy key", exact: true }).waitFor();
assert.deepEqual(calls.at(-1), { method: "POST", path: "/api/account/runtime/agent-a/key" });
failRevoke = true;
await page.getByRole("button", { name: "revoke access key", exact: true }).click();
await page.getByRole("alert").waitFor();
assert.match(await page.getByRole("alert").innerText(), /Key storage temporarily unavailable/);
assert.equal(await page.getByRole("button", { name: "copy key", exact: true }).count(), 1);
failRevoke = false;
await page.getByRole("button", { name: "revoke access key", exact: true }).click();
await page.getByRole("status").filter({ hasText: "access key revoked" }).waitFor();
assert.equal(await page.getByRole("button", { name: "copy key", exact: true }).count(), 0);
assert.deepEqual(calls.at(-1), { method: "DELETE", path: "/api/account/runtime/agent-a/key" });
resolveGenerate = true;
await page.getByRole("button", { name: "generate access key", exact: true }).click();
await page.getByRole("button", { name: "revoke access key", exact: true }).isDisabled().then(disabled => assert.equal(disabled, true));
await page.getByRole("button", { name: "switch agent", exact: true }).click();
resolveGenerate(); resolveGenerate = undefined;
await page.getByText("selected: agent-b", { exact: true }).waitFor();
await page.locator("summary").click();
assert.equal(await page.getByRole("button", { name: "copy key", exact: true }).count(), 0);
assert.equal(await page.getByRole("status").count(), 0);
await page.getByRole("button", { name: "revoke access key", exact: true }).click();
await page.getByRole("status").filter({ hasText: "access key revoked" }).waitFor();
assert.deepEqual(calls.at(-1), { method: "DELETE", path: "/api/account/runtime/agent-b/key" });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
assert.deepEqual(errors, []);
await browser.close();
console.log("Access key revocation clears local access, reports failures, targets the selected agent and isolates delayed key responses.");
