import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const origin = process.env.TAB_TEST_ORIGIN || 'http://127.0.0.1:5222';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 390, height: 1000 } });
const wallets = ['0x1111111111111111111111111111111111111111', '0x2222222222222222222222222222222222222222'];
const token = '0xf07449517ae4b48808098c573a5347e67c714444';
let statuses = ['disabled', 'not_holder'], fail = false, delayWallet = '', challenges = 0, verifies = 0, revoked = 0, generated = 0, tamper = false;
const errors = []; page.on('pageerror', error => errors.push(error.message));
function status(wallet) { const value = statuses[wallets.indexOf(wallet)] || 'wallet_required'; return { status: value, enforced: value !== 'disabled', eligible: value === 'eligible', chain_id: 56, wallet, token_address: value === 'not_configured' || value === 'disabled' ? null : token, balance_units: value === 'eligible' ? '1' : value === 'not_holder' ? '0' : null, minimum_units: '1', decimals: 18, checked_at: new Date().toISOString(), message: ({ disabled: 'Holder access is not enabled.', eligible: 'TAB holding verified. Feature readiness still applies.', not_holder: 'This wallet needs TAB for new actions.', wallet_unverified: 'Verify this wallet before checking TAB.', not_configured: 'The official TAB token is awaiting verification.' })[value] || 'Connect a wallet.', recovery_allowed: true }; }
await page.route('**/api/**', async route => {
  const url = new URL(route.request().url()), path = url.pathname; let data;
  if (path === '/api/account/holder-access') { const wallet = url.searchParams.get('wallet'); if (fail) return route.fulfill({ status: 503, json: { detail: 'Holder RPC unavailable.' } }); data = status(wallet); if (delayWallet === wallet) { delayWallet = ''; await new Promise(resolve => setTimeout(resolve, 500)); } }
  else if (path.endsWith('/holder-access/challenge')) { challenges++; const wallet = route.request().postDataJSON().wallet, id = 'holder-proof-' + challenges, expires_at = new Date(Date.now() + 300000).toISOString(); data = { id, wallet, chain_id: 56, expires_at, message: `tabagents.io\nBNB Smart Chain mainnet 56\nVerify TAB holder access\nAccount: did:privy:holder-qa\nWallet: ${wallet}\nNonce: ${id}\nExpires: ${expires_at}\nThis signature proves wallet control for TAB holder access. It does not authorize a transaction.` }; if (tamper) data.message += '\nApprove spending'; }
  else if (path.endsWith('/holder-access/verify')) { verifies++; const body = route.request().postDataJSON(); assert.match(body.signature, /^0x[a-f0-9]{130}$/); statuses[0] = 'eligible'; data = status(wallets[0]); }
  else if (path.endsWith('/key')) { if (route.request().method() === 'DELETE') { revoked++; data = {}; } else { generated++; data = { key: 'fixture-only-key' }; } }
  else if (path === '/api/account/runtime') { assert.equal(route.request().headers()['x-tab-holder-wallet'], wallets[0]); assert.equal(route.request().headers()['idempotency-key'], 'saved-draft'); assert.equal(route.request().headers().authorization, 'Bearer qa-token'); data = {}; }
  else if (path === '/api/x402/system') data = { settlement_enabled: false, merchants: [{ id: 'qa-provider', recipient: token, capability_status: 'quote_ready', settlement_enabled: true }] };
  else if (path.endsWith('/x402')) data = [];
  else throw Error('Unexpected route ' + path);
  return route.fulfill({ json: data });
});
async function fresh(value) { statuses = [value, 'not_holder']; fail = false; tamper = false; await page.goto(origin + '/tests/holder-access.html', { waitUntil: 'networkidle' }); await page.evaluate(() => { sessionStorage.clear(); localStorage.clear(); }); }
async function refresh() { await page.getByRole('button', { name: 'Refresh TAB holder access' }).click(); await page.getByText('Checking this wallet’s access…').waitFor({ state: 'hidden' }); }
try {
  await fresh('disabled'); assert.equal(await page.getByRole('button', { name: 'create agent', exact: true }).isEnabled(), true); await page.getByText('Holder access is not enabled.', { exact: true }).waitFor(); assert.equal(await page.getByText('0.000000000000000001 TAB', { exact: false }).count(), 0);
  await fresh('not_configured'); assert.equal(await page.getByRole('button', { name: 'create agent', exact: true }).isDisabled(), true); assert.equal(await page.getByRole('button', { name: 'verify wallet access' }).count(), 0); assert.equal(await page.getByRole('link', { name: 'view TAB contract' }).count(), 0); await page.getByRole('link', { name: 'browse the public garden' }).waitFor();
  await fresh('wallet_unverified'); await page.getByRole('button', { name: 'verify wallet access' }).click(); await page.getByText('TAB holding verified. Feature readiness still applies.', { exact: true }).waitFor(); assert.equal(await page.getByRole('button', { name: 'create agent', exact: true }).isEnabled(), true); await page.getByText('0.000000000000000001 TAB', { exact: false }).waitFor(); assert.equal(await page.evaluate(() => document.body.dataset.sent), undefined); assert.equal(await page.evaluate(() => Object.values(localStorage).some(value => value.includes('signature'))), false); assert.equal(verifies, 1); assert.equal(await page.getByRole('link',{name:'view TAB contract'}).getAttribute('href'), 'https://bscscan.com/address/'+token);
  await page.getByLabel('payment provider').selectOption('qa-provider'); assert.equal(await page.getByRole('button', { name: 'request price' }).isDisabled(), true, 'holder eligibility never bypasses settlement readiness');
  // A response for the old wallet cannot restore eligibility after switching.
  delayWallet = wallets[0]; await page.getByRole('button', { name: 'Refresh TAB holder access' }).click(); await page.getByLabel('selected wallet').selectOption(wallets[1]); assert.equal(await page.getByRole('button', { name: 'create agent', exact: true }).isDisabled(), true); await page.getByText('This wallet needs TAB for new actions.', { exact: true }).waitFor(); await page.waitForTimeout(600); assert.equal(await page.getByRole('button', { name: 'create agent', exact: true }).isDisabled(), true);
  await fresh('eligible'); statuses[0] = 'not_holder'; await page.getByRole('button', { name: 'review new action' }).click(); await page.getByRole('status').filter({ hasText: 'This wallet needs TAB for new actions.' }).waitFor(); assert.equal(await page.getByRole('button', { name: 'create agent', exact: true }).isDisabled(), true, 'fresh eligibility check blocks a prepared new action after holder balance is lost');
  await page.getByText('connect your own agent', { exact: true }).click(); assert.equal(await page.getByRole('button', { name: 'generate access key' }).isDisabled(), true); await page.getByRole('button', { name: 'revoke access key' }).click(); assert.equal(revoked, 1); assert.equal(generated, 0); fail = true; await refresh(); await page.getByText('Holder RPC unavailable.', { exact: true }).waitFor(); await page.getByRole('button', { name: 'repay existing credit' }).click(); await page.getByRole('status').filter({ hasText: 'repay_credit allowed' }).waitFor(); await page.getByRole('button', { name: 'withdraw existing backing' }).click(); await page.getByRole('status').filter({ hasText: 'withdraw_backing allowed' }).waitFor(); await page.getByRole('button', { name: 'revoke access key' }).click(); assert.equal(revoked, 2, 'holder RPC outages cannot trap recovery controls');
  await fresh('wallet_unverified'); await page.evaluate(() => sessionStorage.setItem('qa:reject', '1')); const before = verifies; await page.getByRole('button', { name: 'verify wallet access' }).click(); await page.getByRole('alert').filter({ hasText: 'Wallet proof rejected.' }).waitFor(); assert.equal(verifies, before); await page.evaluate(() => sessionStorage.clear()); tamper = true; await page.getByRole('button', { name: 'verify wallet access' }).click(); await page.getByRole('alert').filter({ hasText: 'Nothing was signed.' }).waitFor(); assert.equal(await page.evaluate(() => document.body.dataset.signed), undefined); tamper = false;
  const guards = await page.evaluate(async ({ wallet, token }) => {
    const m = await import('/src/lib/holder-access.ts'); const account = 'did:privy:qa', id = 'qa-proof', expires_at = new Date(Date.now() + 300000).toISOString();
    const base = { id, wallet, expires_at, chain_id: 56, message: `tabagents.io\nBNB Smart Chain mainnet 56\nVerify TAB holder access\nAccount: ${account}\nWallet: ${wallet}\nNonce: ${id}\nExpires: ${expires_at}\nThis signature proves wallet control for TAB holder access. It does not authorize a transaction.` };
    m.validateHolderChallenge(base, account, wallet); let rejected = 0;
    for (const change of [x => x.chain_id = 1, x => x.wallet = token, x => x.id = 'other', x => x.expires_at = new Date(0).toISOString(), x => x.message = x.message.replace(account, 'did:privy:other'), x => x.message += '\nextra']) { const value = structuredClone(base); change(value); try { m.validateHolderChallenge(value, account, wallet); } catch { rejected++; } }
    const selected = m.holderCreationOptions('/account/runtime', { method: 'POST', headers: { 'Idempotency-Key': 'saved-draft', 'X-Tab-Holder-Wallet': token } }, wallet);
    if (new Headers(selected.headers).get('X-Tab-Holder-Wallet') !== wallet || new Headers(selected.headers).get('Idempotency-Key') !== 'saved-draft') throw Error('Creation did not bind the exact selected wallet while retaining idempotency.');
    const api = await import('/src/lib/api.ts'); await api.request('/account/runtime', selected, 'qa-token');
    for (const path of ['/account/runtime/agent/run', '/account/runtime/agent/register', '/account/holder-access', '/account/unknown']) {
      const options = m.holderCreationOptions(path, { method: 'POST' }, wallet);
      if (new Headers(options.headers).has('X-Tab-Holder-Wallet')) throw Error('Creation wallet header leaked into an agent-bound or unknown path.');
    }
    const recoveries = ['withdraw_bnb','withdraw_backing','withdraw_spending','unstake','settle_bond','resolve_outcome','claim_outcome','revoke_session','repay_credit','withdraw_credit','close_credit','pledge_collateral','withdraw_collateral','liquidate_credit','finance_pool_redeem','finance_stock_redeem','finance_advance_repay','finance_advance_close','finance_stock_repay','finance_stock_add_collateral','finance_stock_withdraw','finance_stock_liquidate','job_submit','job_accept','job_reject','job_cancel','job_close_branch','job_pause'];
    return { rejected, recoveries: recoveries.every(x => m.holderRecoveryAction(x)), paused: m.holderRecoveryAction('pause_agent', { paused: true }), resumed: m.holderRecoveryAction('pause_agent', { paused: false }), newRisk: ['unknown','run','job_fund','job_delegate','open_credit','accept_credit','spend_credit','finance_stock_borrow','x402'].some(x => m.holderRecoveryAction(x)), missing: m.holderPermitted(null), disabled: m.holderPermitted({ status: 'disabled', enforced: false, eligible: false }) };
  }, { wallet: wallets[0], token });
  assert.deepEqual(guards, { rejected: 6, recoveries: true, paused: true, resumed: false, newRisk: false, missing: false, disabled: true });
  await fresh("not_holder");
  for (const width of [320, 390, 1280]) { await page.setViewportSize({ width, height: 1000 }); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true); if (width !== 320) await page.screenshot({ path: `/tmp/tab-holder-access-${width}.png`, fullPage: true }); }
  assert.deepEqual(errors, []); console.log('Holder access passed: exact wallet proof, no transaction/signature storage, one-unit balance, disabled-policy distinction, fail-closed missing token/RPC, wallet-switch race, recheck before new actions, recovery availability, readiness preservation and mobile layouts.');
} finally { await browser.close(); }
