import {chromium} from '../node_modules/playwright/index.mjs';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const origin=process.env.TAB_TEST_ORIGIN || 'http://127.0.0.1:5197';
const fixture=JSON.parse(readFileSync(new URL('./jobs-data.json',import.meta.url)));
for(const job of [...fixture.jobs,...fixture.public]) job.deadline=new Date(Date.now()+(job.parent_id?3:4)*3600000).toISOString();
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/**',r=>{
 const path=new URL(r.request().url()).pathname;
 const data=path==='/api/config'?{app_id:null,chain_id:56,network:'mainnet',financial_actions_enabled:false,contracts_status:'not_deployed',gas_sponsorship_enabled:false,payments_enabled:false,agent_execution_enabled:false}:path==='/api/overview'?{mode:'public',summary:{credit_limit:0,spent:0,repaid:0,outstanding:0,agents:0},agents:[],receipts:[],series:[]}:path==='/api/registry'?{status:'not_deployed',agents:[],transactions:[]}:[];
 return r.fulfill({json:data});
});
await page.route('**/fixture',r=>r.fulfill({json:fixture}));
await page.route('**/api/jobs/system',r=>r.fulfill({json:{status:'not_deployed',chain_id:56,network:'mainnet'}}));
await page.route('**/api/jobs/services',r=>r.fulfill({json:[]}));
await page.route('**/api/agents/live',r=>r.fulfill({json:fixture.agents}));
await page.route('**/api/jobs',r=>r.fulfill({json:fixture.public}));
await page.goto(`${origin}/agents`,{waitUntil:'networkidle'});
assert.equal(await page.locator('.garden-stage canvas').count(),1);
assert.equal(await page.locator('.garden-job').count(),1);
await page.locator('.garden-job>summary').click();
await page.getByText('check the block hash',{exact:true}).count();
await page.screenshot({path:new URL('../../qa/garden-jobs-desktop.png',import.meta.url).pathname,fullPage:true});
await page.goto(`${origin}/tests/jobs.html`,{waitUntil:'networkidle'});
await page.getByRole('button',{name:'give it a job',exact:true}).click();
await page.getByLabel('job name',{exact:true}).fill('observe the next block');
await page.getByLabel('what counts as done?',{exact:true}).fill('provide the exact confirmed block hash');
await page.getByRole('button',{name:'save job terms'}).click();
await page.getByRole('alert').waitFor();
const input=JSON.parse(await page.evaluate(()=>document.body.dataset.input));
assert.equal(input.budget,'5');assert.deepEqual(input.tools,['bnb-rpc']);
await page.getByRole('button',{name:'cancel',exact:true}).click();
await page.locator('.owned-job').filter({hasText:'observe a confirmed block'}).click();
await page.getByRole('button',{name:'delegate a branch'}).click();
assert.equal(await page.getByLabel('total budget · USDT',{exact:true}).getAttribute('max'),'4');
assert.equal(await page.getByLabel('per-call cap · USDT',{exact:true}).getAttribute('max'),'0.1');
await page.screenshot({path:new URL('../../qa/job-branch-desktop.png',import.meta.url).pathname,fullPage:true});
for(const width of [320,390,768]){
 await page.setViewportSize({width,height:900});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:new URL(`../../qa/job-branch-${width}.png`,import.meta.url).pathname,fullPage:true});
 await page.goto(`${origin}/agents`,{waitUntil:'networkidle'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:new URL(`../../qa/garden-jobs-${width}.png`,import.meta.url).pathname,fullPage:true});
 await page.goto(`${origin}/tests/jobs.html`,{waitUntil:'networkidle'});
 await page.locator('.owned-job').filter({hasText:'observe a confirmed block'}).click();await page.getByRole('button',{name:'delegate a branch'}).click();
}
await page.route('**/api/jobs/system',r=>r.fulfill({json:{status:'live',chain_id:56,network:'mainnet'}}));
const branch=fixture.jobs.find(j=>j.parent_id),root=fixture.jobs.find(j=>!j.parent_id);
branch.state='submitted';branch.funding='funded';root.funding='funded';root.requester_id='outside-buyer';
await page.goto(`${origin}/tests/jobs.html`,{waitUntil:'networkidle'});
await page.locator('.owned-job').filter({hasText:branch.title}).click();
assert.equal(await page.getByRole('button',{name:'accept evidence and pay',exact:true}).count(),0,'delegating executor cannot approve its own child reward');
root.requester_id=fixture.agents[0].id;
await page.goto(`${origin}/tests/jobs.html`,{waitUntil:'networkidle'});
await page.locator('.owned-job').filter({hasText:branch.title}).click();
assert.equal(await page.getByRole('button',{name:'accept evidence and pay',exact:true}).count(),1,'root buyer can review a submitted child job');
fixture.walletMode=true;await page.goto(`${origin}/tests/jobs.html`,{waitUntil:'networkidle'});await page.locator('.owned-job').filter({hasText:branch.title}).click();
await page.getByRole('button',{name:'accept evidence and pay',exact:true}).click();await page.evaluate(()=>localStorage.setItem('qa:job-send-mode','rejected'));await page.getByRole('button',{name:'sign accept',exact:true}).click();await page.getByText('Wallet request rejected.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'sign accept',exact:true}).count(),1,'an explicit wallet rejection allows retry');
await page.evaluate(()=>localStorage.setItem('qa:job-send-mode','unknown'));await page.getByRole('button',{name:'sign accept',exact:true}).click();await page.getByText('RPC response lost.',{exact:true}).waitFor();await page.reload({waitUntil:'networkidle'});assert.equal(await page.getByRole('button',{name:'sign accept',exact:true}).count(),0,'unknown no-hash submission survives reload without server pending state');await page.getByLabel('submitted job transaction hash',{exact:true}).fill('0x'+'a'.repeat(64));await page.getByRole('button',{name:'check confirmation',exact:true}).click();await page.locator('.job-wallet-review').waitFor({state:'detached'});assert.ok(await page.evaluate(()=>document.body.dataset.submitted),'manual reconciliation records the submitted hash before confirmation');assert.equal(await page.evaluate(()=>localStorage.getItem('tab-job-action:qa-job-intent')),null);
assert.deepEqual(errors,[]);await browser.close();console.log('Original garden, job disclosures, draft bounds, root buyer approval at every depth and mobile layouts passed.');
