import { chromium } from '../node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
const origin = process.env.TAB_TEST_ORIGIN || 'http://127.0.0.1:5197';
mkdirSync('../qa', { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
let release;
const gate = new Promise((resolve) => { release = resolve; });
let illustrationRequests=0;
const mockRealData=async route=>{const path=new URL(route.request().url()).pathname;let data=[];if(path==='/api/config'){await gate;data={app_id:null,chain_id:56,network:'mainnet',contracts_status:'not_deployed',financial_actions_enabled:false};}else if(path==='/api/registry')data={status:'not_deployed',agents:[],transactions:[]};else if(path==='/api/overview'){illustrationRequests++;return route.fulfill({status:410,json:{detail:'Illustration removed.'}});}return route.fulfill({json:data});};
await page.route('**/api/**',mockRealData);
await page.goto(origin+'/live', { waitUntil: 'domcontentloaded' });
await page.locator('.hero-art.is-visible').waitFor({ state: 'attached' });
const delays = await page.evaluate(() => ['.hero-art', '.hero h1'].map((s) => parseFloat(getComputedStyle(document.querySelector(s)).transitionDelay)));
assert(delays[0] > delays[1], 'art must enter separately after title');
assert.equal(await page.locator('.loading-bar').count(), 1, 'art must appear while data is still loading');
await page.waitForFunction(()=>{const node=[...document.querySelectorAll('.hero-art .draw')].at(-1);const value=node?parseFloat(getComputedStyle(node).strokeDashoffset):1;return value>0&&value<1;},null,{timeout:5000});
const before = await page.locator('.hero-art .draw').last().evaluate((el) => parseFloat(getComputedStyle(el).strokeDashoffset));
assert(before > 0 && before < 1, `drawing should be in progress: ${before}`);
release();
await page.waitForTimeout(2100);
assert.equal(await page.locator('.loading-bar').count(),0,'real provider/config reads release the page loading state');
assert.equal(await page.locator('.metric,.chart-panel,.terminal').count(),0,'retired illustrative credit surfaces stay absent');
const after = await page.locator('.hero-art .draw').last().evaluate((el) => parseFloat(getComputedStyle(el).strokeDashoffset));
assert(after < before, 'drawing must advance');
assert.equal(await page.locator('.bird-render').count(), 0);
assert.equal(await page.locator('.hero.reveal-item, .dashboard-grid.reveal-item, .metrics.reveal-item').count(), 0);
await page.screenshot({ path: '../qa/drawn-birds-desktop.png' });
await page.getByRole('link', { name: 'garden', exact: true }).click();
await page.locator('.page-intro h1.is-visible').waitFor({ state: 'attached' });
await page.waitForTimeout(1500);
await page.locator('.agents-panel').scrollIntoViewIfNeeded();
await page.waitForTimeout(1400);
await page.screenshot({ path: '../qa/drawn-birds-agents.png' });
for (const width of [1440, 390]) {
 const reduced = await browser.newPage({ viewport: { width, height: 900 }, reducedMotion: 'reduce' });
 await reduced.route('**/api/**',mockRealData);
 for (const route of ['/', '/agents', '/agents/wren', '/backing', '/providers', '/activity', '/protocol', '/account']) {
  await reduced.goto(origin + route, { waitUntil: 'networkidle' });
  const status = await reduced.evaluate(() => ({ width: document.body.scrollWidth, viewport: innerWidth, hidden: [...document.querySelectorAll('.reveal-item')].filter((el) => getComputedStyle(el).opacity !== '1').length }));
  assert.equal(status.width<=status.viewport, true, `overflow ${width} ${route}`);
  assert.equal(status.hidden, 0, `hidden reduced-motion content ${route}`);
  if (width === 390 && route === '/') await reduced.screenshot({ path: '../qa/drawn-birds-mobile.png' });
 }
 await reduced.close();
}
assert.deepEqual(errors, []);
assert.equal(illustrationRequests,0,'motion must never depend on a fabricated dataset');
await browser.close();
console.log('Independent art timing, SVG drawing, route reveals, and desktop/mobile reduced-motion checks passed.');
