import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const origin=process.env.TAB_TEST_ORIGIN||'http://127.0.0.1:5198';
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:390,height:900}});
page.setDefaultTimeout(10000);
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const owner='0x1111111111111111111111111111111111111111', recipient='0x2222222222222222222222222222222222222222', usdt='0x55d398326f99059fF775485246999027B3197955';
const merchant={id:'qa-provider',recipient,resource_url:'https://qa.example/paid',capability_status:'quote_ready',settlement_enabled:true};
const system={status:'configured',network:'eip155:56',currency:'USDT',asset:usdt,merchants:[merchant],settlement_enabled:true};
const hash='0x'+'a'.repeat(64),creditId='b'.repeat(64);
let history=[],creditPending=[],confirmed=false,executeCount=0,prepareCount=0,quote,lastIntent=null;const prepared=[];
const credit={id:creditId,agent_id:'agent-a',onchain_agent_id:'0x'+'1'.repeat(64),lender:recipient,borrower:owner,signer:owner,role:'borrower',funded:'3',available:'2',outstanding:'1',total_spent:'1',total_repaid:'0',withdrawn:'0',per_call:'1',daily_cap:'5',expires_at:Math.floor(Date.now()/1000)+3600,tools:['x402'],recipients:[recipient],accepted:true,closed:false,status:'active',interest_bps:0,secured:false,actions:{accept:true,repay:true,withdraw:true,close:true,spend:true}};
await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;let data;
 if(path==='/api/x402/system')data=system;
 else if(path==='/api/credit/assets')data={chain_id:56,currency:'USDT',assets:[{address:usdt,symbol:'USDT',decimals:18,borrowing_enabled:true,borrowing_status:'ready'}]};
 else if(path==='/api/agents/live')data=[];
 else if(path.endsWith('/credit'))data={chain_id:56,currency:'USDT',agreements:[credit],pending_intents:creditPending};
 else if(path.endsWith('/x402'))data=history;
 else if(path.endsWith('/x402/quote'))data=quote;
 else if(path.endsWith('/execute')){executeCount++;history=[{quote_id:'quote-1',provider:merchant.id,status:'uncertain',amount:'0.000000000000000001',expires_at:quote.expires_at,tx_hash:null}];return route.fulfill({status:503,json:{detail:'The provider response was lost. Reconcile the payment.'}});}
 else if(path.endsWith('/release-expired')){history=[{...history[0],status:'cancelled'}];data={status:'cancelled'};}
 else if(path.endsWith('/reconcile')){history=[{...history[0],status:'confirmed',tx_hash:hash}];data=history[0];}
 else if(path.endsWith('/wallet-actions/prepare')){prepareCount++;const body=route.request().postDataJSON();prepared.push(body);creditPending=[{id:'intent-1',agent_id:'agent-a',action:body.action,chain_id:56,network:'mainnet',sender:owner,to:recipient,data:'0x12345678',value:'0x0',transactions:[{to:recipient,data:'0x12345678',value:'0x0',chainId:56}],expires_at:new Date(Date.now()+600000).toISOString(),details:body}];data=creditPending[0];lastIntent=data;}
 else if(path.endsWith('/wallet-actions/intent-1/submitted')){data={status:'submitted'};}
 else if(path.endsWith('/wallet-actions/intent-1/confirm')){confirmed=true;creditPending=[];data={status:'confirmed'};}
 else if(path.includes('/bnb/transactions/'))data={status:'confirmed'};
 else throw Error(`Unexpected endpoint ${path}`);
 await route.fulfill({json:data});
});
try {
 await page.goto(`${origin}/tests/payments.html`,{waitUntil:'networkidle'});
 const validation=await page.evaluate(async({owner,merchant})=>{
   const p=await import('/src/lib/payments.ts'),v=await import('/node_modules/.vite/deps/viem.js');const now=Math.floor(Date.now()/1000);
   const offer={amount_units:'1',resource:{url:merchant.resource_url},accepted:{amount:'1',asset:'0x55d398326f99059fF775485246999027B3197955',network:'eip155:56',payTo:merchant.recipient,extra:{assetTransferMethod:'permit2'}}};
   const types={EIP712Domain:[{name:'name',type:'string'},{name:'chainId',type:'uint256'},{name:'verifyingContract',type:'address'}],PermitWitnessTransferFrom:[{name:'permitted',type:'TokenPermissions'},{name:'spender',type:'address'},{name:'nonce',type:'uint256'},{name:'deadline',type:'uint256'},{name:'witness',type:'Witness'}],TokenPermissions:[{name:'token',type:'address'},{name:'amount',type:'uint256'}],Witness:[{name:'to',type:'address'},{name:'validAfter',type:'uint256'}]};
   const quote={quote_id:'quote-1',provider:merchant.id,sender:owner,chain_id:56,currency:'USDT',status:'requires_wallet_authorization',expires_at:now+120,offer,typed_data:{domain:{name:'Permit2',chainId:56,verifyingContract:p.PERMIT2},primaryType:'PermitWitnessTransferFrom',types,message:{permitted:{token:offer.accepted.asset,amount:'1'},spender:p.EXACT_PROXY,nonce:'1',deadline:String(now+120),witness:{to:merchant.recipient,validAfter:String(now-5)}}}};
   p.validatePaymentQuote(quote,merchant,owner,'1','5');
   let refused=0;for(const mutate of [q=>q.chain_id=1,q=>q.sender=merchant.recipient,q=>q.offer.accepted.payTo=owner,q=>q.typed_data.domain.verifyingContract=owner,q=>q.typed_data.message.permitted.amount='2',q=>q.typed_data.message.spender=owner,q=>q.typed_data.message.deadline=String(now-1),q=>q.typed_data.types.Witness[0].type='bytes32']){const q=structuredClone(quote);mutate(q);try{p.validatePaymentQuote(q,merchant,owner,'1','5');}catch{refused++;}}
   const approval={...quote,status:'approval_required',typed_data:undefined,transactions:[{to:offer.accepted.asset,data:v.encodeFunctionData({abi:v.erc20Abi,functionName:'approve',args:[p.PERMIT2,1n]}),value:'0x0',chainId:56}]};p.validatePaymentQuote(approval,merchant,owner,'1','5');
   let unlimitedRejected=false;approval.transactions[0].data=v.encodeFunctionData({abi:v.erc20Abi,functionName:'approve',args:[p.PERMIT2,2n**256n-1n]});try{p.validatePaymentQuote(approval,merchant,owner,'1','5');}catch{unlimitedRejected=true;}
   const calls=[];const wallet={address:owner,switchChain:async()=>{},getEthereumProvider:async()=>({request:async({method,params})=>{calls.push([method,params]);if(method==='eth_chainId')return '0x38';if(method==='eth_accounts')return [owner];if(method==='eth_signTypedData_v4')return '0x'+'a'.repeat(130);throw Error(method);}})};await p.signPaymentQuote(wallet,quote,merchant,owner,'1','5');
   return {quote,refused,unlimitedRejected,signatures:calls.filter(c=>c[0]==='eth_signTypedData_v4').length};
 },{owner,merchant});
 quote=validation.quote;assert.equal(validation.refused,8);assert.equal(validation.unlimitedRejected,true);assert.equal(validation.signatures,1);
 await page.getByLabel('payment provider',{exact:true}).selectOption(merchant.id);await page.getByRole('button',{name:'request price',exact:true}).click();await page.getByRole('button',{name:'authorize & request'}).click();await page.getByText('This request may have settled.',{exact:false}).waitFor();assert.equal(await page.getByRole('button',{name:'request price',exact:true}).isDisabled(),true);assert.equal(executeCount,1);
 await page.reload({waitUntil:'networkidle'});assert.equal(await page.getByRole('button',{name:'request price',exact:true}).isDisabled(),true,'uncertain submissions survive refresh');await page.getByLabel('BNB Chain transaction hash').fill(hash);await page.getByRole('button',{name:'verify payment',exact:true}).click();await page.getByText('Payment confirmed from its onchain receipt.',{exact:true}).waitFor();assert.equal(executeCount,1,'reconcile must not repay');
 history=[{quote_id:'quote-expired',provider:merchant.id,status:'uncertain',amount:'1',expires_at:1,tx_hash:null}];await page.evaluate(()=>sessionStorage.clear());await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'check expired payment',exact:true}).click();await page.getByText('Expired authorization checked onchain.',{exact:false}).waitFor();await page.getByLabel('payment provider',{exact:true}).selectOption(merchant.id);assert.equal(await page.getByRole('button',{name:'request price',exact:true}).isDisabled(),false,'only server-verified expired unused authorization can release recovery');assert.equal(executeCount,1);

 const amount=page.getByLabel(`Amount for ${creditId}`);await amount.fill('1.000000000000000001');await page.getByRole('button',{name:'repay credit',exact:true}).click();await page.getByText('Enter an amount up to 1 USDT.',{exact:true}).waitFor();assert.equal(prepareCount,0);await amount.fill('0.000000000000000001');await page.getByRole('button',{name:'repay credit',exact:true}).click();await page.getByRole('button',{name:'confirm in wallet',exact:true}).click();await page.getByText('Credit transaction confirmed.',{exact:true}).waitFor();assert.equal(confirmed,true);assert.equal(prepareCount,1);assert.equal(prepared[0].amount,'0.000000000000000001');
 for(const action of ['accept','withdraw','close']){if(action==='withdraw')await amount.fill('2');await page.getByRole('button',{name:`${action} credit`,exact:true}).click();await page.getByRole('button',{name:'confirm in wallet',exact:true}).click();await page.getByText('Credit transaction confirmed.',{exact:true}).waitFor();}
 await page.getByText('open a credit agreement',{exact:true}).click();await page.getByLabel('authorized payment signer',{exact:true}).fill(owner);await page.getByLabel('funding in USDT',{exact:true}).fill('1.000000000000000001');await page.getByLabel('USDT per day',{exact:true}).fill('1');await page.locator('fieldset').filter({hasText:'approved recipients'}).getByRole('checkbox').check();await page.getByRole('button',{name:'review credit terms',exact:true}).click();await page.getByRole('button',{name:'confirm in wallet',exact:true}).click();await page.getByText('Credit transaction confirmed.',{exact:true}).waitFor();assert.deepEqual(prepared.map(p=>p.action),['repay_credit','accept_credit','withdraw_credit','close_credit','open_credit']);assert.deepEqual(prepared.at(-1).recipients,[recipient]);assert.equal(prepared.at(-1).amount,'1.000000000000000001');
 await page.getByText('authorized merchant payment',{exact:true}).click();await page.getByLabel('credit payment amount · USDT',{exact:true}).fill('0.01');await page.getByLabel('Credit payment recipient',{exact:true}).selectOption(recipient);await page.getByLabel('Credit payment tool',{exact:true}).selectOption('x402');await page.getByLabel('request commitment',{exact:true}).fill('0x'+'1'.repeat(64));await page.getByLabel('receipt commitment',{exact:true}).fill('0x'+'0'.repeat(64));await page.getByRole('button',{name:'review merchant payment',exact:true}).click();await page.getByText('Choose an approved recipient and tool, with nonzero 32-byte request and receipt commitments.',{exact:true}).waitFor();assert.equal(prepareCount,5);await page.getByLabel('receipt commitment',{exact:true}).fill('0x'+'2'.repeat(64));await page.getByRole('button',{name:'review merchant payment',exact:true}).click();await page.getByRole('button',{name:'confirm in wallet',exact:true}).click();await page.getByText('Credit transaction confirmed.',{exact:true}).waitFor();assert.equal(prepared.at(-1).action,'spend_credit');assert.equal(prepared.at(-1).amount,'0.01');

 await page.evaluate(({hash,intent})=>localStorage.setItem('tab:credit:pending:agent-a',JSON.stringify({id:intent.id,hash,intent})),{hash,intent:{...lastIntent,expires_at:new Date(Date.now()-60000).toISOString()}});await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'verify credit transaction',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'confirm in wallet',exact:true}).count(),0,'a locally submitted expired intent must survive missing server pending state without a second wallet send');await page.getByRole('button',{name:'verify credit transaction',exact:true}).click();await page.getByText('Credit transaction confirmed.',{exact:true}).waitFor();assert.equal(prepareCount,6);

 await page.evaluate(()=>localStorage.setItem('qa:credit-send-mode','rejected'));await page.getByRole('button',{name:'accept credit',exact:true}).click();await page.evaluate(()=>localStorage.setItem('qa:credit-send-mode','preflight'));await page.getByRole('button',{name:'confirm in wallet',exact:true}).click();await page.getByText('Connect the wallet that owns this agent.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'confirm in wallet',exact:true}).count(),1,'proven pre-submit failures permit retry without an impossible recovery hash');assert.equal(await page.evaluate(()=>localStorage.getItem('tab:credit:pending:agent-a')),null);await page.evaluate(()=>localStorage.setItem('qa:credit-send-mode','rejected'));await page.getByRole('button',{name:'confirm in wallet',exact:true}).click();await page.getByText('Wallet request rejected.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'confirm in wallet',exact:true}).count(),1,'explicit wallet rejection permits reviewing the same unsigned action');await page.evaluate(()=>localStorage.setItem('qa:credit-send-mode','unknown'));await page.getByRole('button',{name:'confirm in wallet',exact:true}).click();await page.getByText('RPC response lost.',{exact:true}).waitFor();creditPending=[];await page.reload({waitUntil:'networkidle'});assert.equal(await page.getByRole('button',{name:'confirm in wallet',exact:true}).count(),0,'unknown no-hash credit submissions remain blocked after server intent expiry');await page.getByLabel('submitted transaction hash',{exact:true}).fill(hash);await page.getByRole('button',{name:'verify credit transaction',exact:true}).click();await page.getByText('Credit transaction confirmed.',{exact:true}).waitFor();await page.evaluate(()=>{localStorage.removeItem('qa:credit-send-mode');localStorage.setItem('tab:wallet:pending:agent-a',JSON.stringify({intent:{id:'unknown-wallet-action'},hash:'',uncertain:true}));window.dispatchEvent(new Event('tab:wallet-actions-changed'));});await page.getByText('Finish the pending wallet action below before preparing credit changes.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'accept credit',exact:true}).isDisabled(),true,'local unknown wallet action blocks credit even when server pending list is empty');await page.evaluate(()=>{localStorage.removeItem('tab:wallet:pending:agent-a');window.dispatchEvent(new Event('tab:wallet-actions-changed'));});

 credit.secured=true;credit.collateral={token:usdt,decimals:18,amount:'2',value_usdt:'2',borrowing_power_usdt:'1.8',available_borrowing_usdt:'0.8',health_factor:'1.9',oracle_status:'verified',ltv_bps:9000,liquidation_bps:9500,bonus_bps:200,paused:false};credit.actions.pledge=true;credit.actions.withdraw_collateral=true;
 await page.getByRole('button',{name:'refresh credit',exact:true}).click();const collateralAmount=page.getByLabel(`Collateral amount for ${creditId}`);await collateralAmount.fill('0.0000000000000000001');const beforeCollateral=prepareCount;await page.getByRole('button',{name:'pledge collateral',exact:true}).click();await page.getByText('Enter an exact positive collateral amount.',{exact:true}).waitFor();assert.equal(prepareCount,beforeCollateral);await collateralAmount.fill('0.000000000000000001');await page.getByRole('button',{name:'pledge collateral',exact:true}).click();await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'confirm in wallet',exact:true}).click();await page.getByText('Credit transaction confirmed.',{exact:true}).waitFor();assert.equal(prepared.at(-1).action,'pledge_collateral');assert.equal(prepared.at(-1).amount,'0.000000000000000001');assert.equal(prepared.at(-1).token_address,usdt);
 await collateralAmount.fill('3');await page.getByRole('button',{name:'withdraw collateral',exact:true}).click();await page.getByText('The withdrawal exceeds your pledge.',{exact:true}).waitFor();assert.equal(prepareCount,beforeCollateral+1);
 credit.outstanding='0';credit.collateral.oracle_status='unavailable';credit.collateral.health_factor=null;credit.collateral.available_borrowing_usdt=null;await page.getByRole('button',{name:'refresh credit',exact:true}).click();await page.getByText('Collateral pricing is unavailable.',{exact:false}).waitFor();await collateralAmount.fill('2');await page.getByRole('button',{name:'withdraw collateral',exact:true}).click();await page.getByRole('button',{name:'confirm in wallet',exact:true}).click();await page.getByText('Credit transaction confirmed.',{exact:true}).waitFor();assert.equal(prepared.at(-1).action,'withdraw_collateral');
 const collateralGuards=await page.evaluate(async()=>{const {validateWalletActionIntent}=await import('/src/components/AgentWalletActions.tsx');const {encodeFunctionData,erc20Abi}=await import('/node_modules/.vite/deps/viem.js');const wallet='0x1111111111111111111111111111111111111111',token='0x3333333333333333333333333333333333333333',backing='0x2222222222222222222222222222222222222222';const final={to:backing,data:'0x12345678',value:'0x0',chainId:56};const intent={id:'pledge',agent_id:'agent-a',sender:wallet,chain_id:56,action:'pledge_collateral',expires_at:new Date(Date.now()+60000).toISOString(),details:{amount:'0.123456'},to:backing,data:final.data,value:'0x0',transaction:final,transactions:[{to:token,data:encodeFunctionData({abi:erc20Abi,functionName:'approve',args:[backing,123456n]}),value:'0x0',chainId:56},final]};validateWalletActionIntent(intent,{id:'agent-a',wallet},token,6,undefined,true);intent.transactions[0].data=encodeFunctionData({abi:erc20Abi,functionName:'approve',args:[backing,123457n]});try{validateWalletActionIntent(intent,{id:'agent-a',wallet},token,6,undefined,true);return false;}catch{return true;}});assert.equal(collateralGuards,true,'Collateral approvals preserve exact token precision and refuse excess allowance');
 for(const width of [320,390,768]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`financial panels fit ${width}px`);if(width===390)await page.screenshot({path:'../qa/bnb-payment-credit-mobile.png',fullPage:true});}assert.deepEqual(errors,[]);console.log('Permit2 signing/amount/domain/recipient checks, exact approvals, uncertain payment recovery without repay, credit open/accept/repay/withdraw/close, collateral pledge/recovery, exact token approvals, debt-free withdrawal during oracle failure, amount bounds and receipt confirmation passed.');
}catch(error){console.error('page errors',errors);console.error((await page.locator('body').innerText()).slice(0,3000));throw error;}finally{await browser.close();}
