import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const origin=process.env.TAB_TEST_ORIGIN||'http://127.0.0.1:5222';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:900}});page.setDefaultTimeout(12000);
const owner='0x1111111111111111111111111111111111111111',contract='0x2222222222222222222222222222222222222222',id='0123456789abcdef0123456789abcdef',registryId=owner+id.slice(8),hash='0x'+'b'.repeat(64),policy='0x'+'c'.repeat(64);
let agent,challenge,status,submits=0,challenges=0,mode='pending',input,sponsorReady=true;const errors=[];page.on('pageerror',e=>errors.push(e.message));
function reset(){status={status:'not_submitted',retryable:true,request_id:null,tx_hash:null,agent:null};agent={id,name:'wren',daily_cap:'5',registry_address:contract,registry_id:null,registration_tx:null,status:'awaiting_registration',wallet:null};mode='pending';}
reset();
await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;let data;
 if(path==='/api/sponsorship')data={status:sponsorReady?'ready':'unfunded',message:sponsorReady?'Tab covers registration gas.':'The registration sponsor needs a BNB top-up.'};else if(path==='/api/tools')data={'bnb-rpc':true};else if(path==='/api/models')data=[];
 else if(path==='/api/account/runtime'){input=route.request().postDataJSON();agent={...agent,...input};data=agent;}
 else if(path.endsWith('/sponsor/status'))data=status;
 else if(path.endsWith('/challenge')){challenges++;const body=route.request().postDataJSON();assert.equal(body.sponsored,true);const deadline=Math.floor(Date.now()/1000)+600;challenge={sponsored:true,request_id:'request-'+challenges,chain_id:56,registry:contract,registry_id:registryId,wallet:owner,policy_hash:policy,expires_at:new Date(deadline*1000).toISOString(),typed_data:{domain:{name:'Tab Protocol',version:'1',chainId:56,verifyingContract:contract},primaryType:'Register',types:{Register:[{name:'id',type:'bytes32'},{name:'owner',type:'address'},{name:'name',type:'string'},{name:'dailyCap',type:'uint256'},{name:'policyHash',type:'bytes32'},{name:'nonce',type:'uint256'},{name:'deadline',type:'uint256'}]},message:{id:registryId,owner,name:agent.name,dailyCap:'5000000000000000000',policyHash:policy,nonce:'0',deadline:String(deadline)}}};data=challenge;}
 else if(path.endsWith('/sponsor')){submits++;const body=route.request().postDataJSON();assert.equal(body.request_id,challenge.request_id);assert.equal(body.wallet,owner);assert.match(body.signature,/^0x[a-f0-9]{130}$/);status={status:'pending',retryable:false,request_id:body.request_id,tx_hash:mode==='lost'?null:hash,agent:null,message:'Registration is pending confirmation.'};if(mode==='lost')return route.fulfill({status:503,json:{detail:'Sponsor response lost. Check registration status.'}});data=status;}
 else throw Error('Unexpected route '+path);return route.fulfill({json:data});});
async function setup(custom=false){await page.getByRole('button',{name:custom?'bring your own':'onchain monitor',exact:false}).click();await page.getByPlaceholder('e.g. wren').fill('wren');await page.getByRole('button',{name:'continue',exact:true}).click();await page.getByRole('button',{name:'continue',exact:true}).click();}
async function fresh(query=''){reset();sponsorReady=!query.includes('unavailable');await page.goto(`${origin}/tests/registration.html${query}`,{waitUntil:'networkidle'});await page.evaluate(()=>localStorage.clear());await page.reload({waitUntil:'networkidle'});}
try{
 await fresh();await setup(true);assert.equal(await page.getByRole('checkbox',{name:'pay registration BNB gas from my wallet'}).isChecked(),false);await page.getByText('your wallet needs no BNB to register.',{exact:false}).waitFor();await page.getByRole('button',{name:'create agent',exact:true}).click();await page.getByRole('button',{name:'check registration',exact:true}).waitFor();assert.equal(input.template,'custom','bring your own uses the same owned-draft sponsorship');assert.equal(submits,1);assert.equal(await page.evaluate(()=>document.body.dataset.sent),undefined);const signed=JSON.parse(await page.evaluate(()=>document.body.dataset.signed));assert.equal(signed.primaryType,'Register');assert.equal(signed.domain.chainId,56);assert.equal(signed.message.owner,owner);let saved=JSON.parse(await page.evaluate(()=>localStorage.getItem('tab:registration:pending:qa')));assert.equal(saved.request_id,challenge.request_id);assert.equal('signature' in saved,false,'owner signature is never persisted');assert.equal(await page.getByLabel('registration transaction hash',{exact:true}).count(),0,'sponsored recovery never demands the sponsor hash from a zero-BNB wallet');
 await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'check registration',exact:true}).click();assert.equal(submits,1,'status recovery cannot submit another authorization');status={...status,status:'confirmed',agent:{...agent,wallet:owner,registry_id:registryId,registration_tx:hash,status:'ready'}};await page.getByRole('button',{name:'check registration',exact:true}).click();await page.getByText('registered wren',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('tab:registration:pending:qa')),null);
 await fresh();mode='lost';await setup();await page.getByRole('button',{name:'create agent',exact:true}).click();await page.getByText('Sponsor response lost. Check registration status.',{exact:true}).waitFor();const before=submits;await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'check registration',exact:true}).click();assert.equal(submits,before,'a lost HTTP response is reconciled without resubmission');await page.evaluate(()=>localStorage.clear());await page.reload({waitUntil:'networkidle'});await setup();const beforeChallenge=challenges;await page.getByRole('button',{name:'create agent',exact:true}).click();await page.getByRole('button',{name:'check registration',exact:true}).waitFor();assert.equal(submits,before);assert.equal(challenges,beforeChallenge,'server-held pending request recovers without a second signature');
 status={...status,status:'failed',retryable:true,message:'Reverted registration verified. Try again.'};await page.getByRole('button',{name:'check registration',exact:true}).click();await page.getByText('Reverted registration verified. Try again.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('tab:registration:pending:qa')),null);
 await fresh();await page.evaluate(()=>localStorage.setItem('qa:registration:reject','1'));await setup();await page.getByRole('button',{name:'create agent',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('tab:registration:pending:qa')),null,'rejected signing creates no uncertain relay record');const rejectedCount=submits;await page.evaluate(()=>localStorage.removeItem('qa:registration:reject'));await page.getByRole('button',{name:'create agent',exact:true}).click();await page.getByRole('button',{name:'check registration',exact:true}).waitFor();assert.equal(submits,rejectedCount+1);
 const guard=await page.evaluate(async({challenge,agent,owner})=>{const m=await import('/src/lib/registration.ts');let rejected=0;const checks=[x=>x.typed_data.domain.name='TabProtocol',x=>x.typed_data.domain.chainId=1,x=>x.typed_data.domain.verifyingContract=owner,x=>x.typed_data.message.owner=x.registry,x=>x.typed_data.message.id='0x'+'0'.repeat(64),x=>x.typed_data.message.name='wrong',x=>x.typed_data.message.dailyCap='1',x=>x.typed_data.message.policyHash='0x'+'0'.repeat(64),x=>x.typed_data.message.deadline='1',x=>x.typed_data.types.Register.push({name:'spender',type:'address'}),x=>x.typed_data.message.nonce='-1'];for(const mutate of checks){const value=structuredClone(challenge);mutate(value);try{m.validateSponsoredChallenge(value,agent,owner);}catch{rejected++;}}return rejected;},{challenge,agent,owner});assert.equal(guard,11,'typed permission binds exact deployed domain, owner, draft, cap, policy and expiry');
 await fresh('?unavailable=1');await setup();const countBefore=challenges;await page.getByRole('button',{name:'create agent',exact:true}).click();await page.getByRole('alert').filter({hasText:'The registration sponsor needs a BNB top-up.'}).waitFor();assert.equal(challenges,countBefore,'unavailable sponsorship never silently falls back to paid wallet sending');assert.equal(await page.evaluate(()=>document.body.dataset.signed),undefined);await page.getByRole('checkbox',{name:'pay registration BNB gas from my wallet'}).check();await page.getByText('Your wallet will send the registration and pay its BNB gas fee.',{exact:false}).waitFor();await page.getByRole('button',{name:'create agent',exact:true}).click();await page.getByText('Explicit wallet-paid path selected; QA does not send funds.',{exact:true}).waitFor();
 for(const width of [320,390,768]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(width===390)await page.screenshot({path:'../qa/sponsored-registration-mobile.png',fullPage:true});}
 assert.deepEqual(errors,[]);console.log('Sponsored registration: zero-BNB owner signature only, bring-your-own flow, exact typed permission, opt-in self-pay, unavailable sponsor, signature rejection, durable lost-response recovery, server recovery, no duplicate submission, failed-attempt release and mobile layouts passed.');
}finally{await browser.close();}
