import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {encodeFunctionData,erc20Abi,parseUnits} from 'viem';
const origin=process.env.TAB_TEST_ORIGIN||'http://127.0.0.1:5198';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:900}});page.setDefaultTimeout(12000);
const owner='0x1111111111111111111111111111111111111111',contract='0x2222222222222222222222222222222222222222',token='0x3333333333333333333333333333333333333333',usdt='0x55d398326f99059ff775485246999027b3197955',hash='0x'+'a'.repeat(64);
let pending=[],prepared=[],confirmations=0,metadataReads=0,lastIntent=null,sequence=0,submitted=[],releaseRequiresSubmit=false;
const job={id:'ab'.repeat(32),executor_id:'agent-a',title:'source review',funding:'funded',state:'open',bond_token_address:token,bond_tokens:'2.000001',penalty_bps:5000,deadline:new Date(Date.now()+86400000).toISOString()};
const bounty={id:'bounty-a',title:'review primary sources',budget:'3.000000000000000001',funding:'unfunded',assigned_agent_id:null};
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;let data;
 if(path.endsWith('/wallet-actions'))data=pending;
 else if(path==='/api/backing/assets')data=[{symbol:'USDT',name:'Tether USD',address:usdt,decimals:18,enabled:true,chain_id:56,category:'usdt'}];
 else if(path==='/api/token/system')data={status:'not_configured',official_tab_address:null,staking_enabled:false};
 else if(path==='/api/x402/system')data={merchants:[{id:'provider',recipient:contract}]};
 else if(path==='/api/jobs'||path==='/api/account/jobs')data=[job];
 else if(path==='/api/bounties'||path==='/api/account/bounties'){if(route.request().method()==='POST'){data={...bounty,...route.request().postDataJSON(),id:'new-bounty'};}else data=[bounty];}
 else if(path==='/api/agents/live')data=[];
 else if(path.startsWith('/api/bnb/tokens/')){metadataReads++;data={chain_id:56,address:token,decimals:6};}
 else if(path.endsWith('/wallet-actions/prepare')){const body=route.request().postDataJSON();prepared.push(body);let tx={to:contract,data:'0x12345678',value:body.action==='back_bnb'?'0x'+parseUnits(body.amount,18).toString(16):'0x0',chainId:'0x38'};let txs=[];if(['back','fund_spending','bond_job','fund_bounty'].includes(body.action)){const decimals=body.action==='bond_job'?6:18;txs.push({to:body.action==='bond_job'?token:usdt,data:encodeFunctionData({abi:erc20Abi,functionName:'approve',args:[contract,parseUnits(body.amount,decimals)]}),value:'0x0',chainId:'0x38'});}txs.push(tx);lastIntent={id:'intent-'+(++sequence),agent_id:'agent-a',action:body.action,chain_id:56,network:'mainnet',sender:owner,...tx,transaction:tx,transactions:txs,expires_at:new Date(Date.now()+600000).toISOString(),details:body};pending=[lastIntent];data=lastIntent;}
 else if(path.endsWith('/submitted')){submitted.push(route.request().postDataJSON().tx_hash);pending=pending.map(i=>({...i,tx_hash:hash}));data={status:'submitted'};}
 else if(path.endsWith('/confirm')){confirmations++;pending=[];data={status:'confirmed'};}
 else if(path.endsWith('/release-failed')){if(releaseRequiresSubmit)assert.equal(submitted.at(-1),hash,'manual reverted hash must be bound before release');pending=[];data={status:'released'};}
 else if(path.includes('/bnb/transactions/'))data={status:'confirmed'};
 else throw Error('Unexpected API '+path);
 await route.fulfill({json:data});
});
const select=async action=>{await page.getByLabel('wallet action',{exact:true}).selectOption(action);};
const prepare=async()=>{await page.getByRole('button',{name:'review wallet action',exact:true}).click();await page.getByRole('button',{name:'confirm wallet action',exact:true}).waitFor();};
const confirm=async()=>{await page.getByRole('button',{name:'confirm wallet action',exact:true}).click();await page.getByText('Wallet action confirmed on BNB Chain.',{exact:true}).waitFor();};
try {
 await page.goto(origin+'/tests/wallet-actions.html',{waitUntil:'networkidle'});
 const guard=await page.evaluate(async({owner,contract,usdt,token})=>{const m=await import('/src/components/AgentWalletActions.tsx');const v=await import('/node_modules/.vite/deps/viem.js');const agent={id:'agent-a',wallet:owner};const final={to:contract,data:'0x12345678',value:'0x0',chainId:'0x38'};const approval={to:usdt,data:v.encodeFunctionData({abi:v.erc20Abi,functionName:'approve',args:[contract,1000000000000000001n]}),value:'0x0',chainId:56};const intent={id:'a',agent_id:'agent-a',sender:owner,action:'fund_spending',expires_at:new Date(Date.now()+600000).toISOString(),chain_id:56,to:contract,data:final.data,value:'0x0',transaction:final,transactions:[approval,final],details:{action:'fund_spending',amount:'1.000000000000000001'}};m.validateWalletActionIntent(intent,agent,usdt,18,intent.details);let refused=0;for(const mutate of [i=>i.chain_id=1,i=>i.sender=contract,i=>i.agent_id='other',i=>i.expires_at=new Date(0).toISOString(),i=>i.to=token,i=>i.transactions[1].value='0x1',i=>i.transactions[0].to=token,i=>i.transactions[0].data=v.encodeFunctionData({abi:v.erc20Abi,functionName:'approve',args:[contract,2n**256n-1n]}),i=>i.transactions[0].data=v.encodeFunctionData({abi:v.erc20Abi,functionName:'approve',args:[token,1000000000000000001n]})]){const changed=structuredClone(intent);mutate(changed);try{m.validateWalletActionIntent(changed,agent,usdt,18);}catch{refused++;}}let precision=0;for(const decimals of [19,-1,6])try{m.validateWalletActionIntent(intent,agent,usdt,decimals);}catch{precision++;}return{refused,precision,rejected:m.walletPromptRejected({cause:{code:4001}}),unknown:m.walletPromptRejected(Error('RPC timeout'))};},{owner,contract,usdt,token});
 assert.deepEqual(guard,{refused:9,precision:3,rejected:true,unknown:false});
 await page.getByLabel('token name',{exact:true}).fill('willow token');await page.getByLabel('token symbol',{exact:true}).fill('WILLOW');await page.getByLabel('public token description or metadata URL').fill('https://example.com/willow');await page.getByLabel('fixed token supply').fill('1000.000000000000000001');await prepare();assert.equal(prepared[0].amount,'1000.000000000000000001');assert.match(prepared[0].metadata_hash,/^0x[0-9a-f]{64}$/);assert.equal(await page.locator('body').getAttribute('data-sends'),null,'review does not sign');
 await page.evaluate(()=>document.body.dataset.mode='rejected');await page.getByRole('button',{name:'confirm wallet action',exact:true}).click();await page.getByText('Wallet request rejected by user.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('tab:wallet:pending:agent-a')),null,'explicit rejection clears uncertain attempt');assert.equal(await page.getByRole('button',{name:'confirm wallet action',exact:true}).count(),1);await page.evaluate(()=>document.body.dataset.mode='');await confirm();assert.equal(prepared.length,1);
 await select('pair_token');await page.getByLabel('existing token contract').fill(token);await prepare();await confirm();
 await select('back');await page.getByLabel('amount in USDT',{exact:true}).fill('0.000000000000000001');await prepare();await confirm();assert.equal(prepared.at(-1).amount,'0.000000000000000001');
 await select('back_bnb');await page.getByLabel('amount in BNB',{exact:true}).fill('0.000000000000000001');await prepare();await confirm();assert.equal(lastIntent.value,'0x1');
 await select('withdraw_bnb');await page.getByRole('checkbox',{name:'withdraw my entire recorded backing'}).check();await prepare();await confirm();assert.equal(prepared.at(-1).amount,'0');
 await select('bind_job_agent');await page.getByLabel('funded job',{exact:true}).selectOption(job.id);await prepare();await confirm();assert.equal(prepared.at(-1).job_id,job.id);
 await select('bond_job');await prepare();await confirm();assert.equal(prepared.at(-1).amount,'2.000001');assert.ok(metadataReads>=2,'paired token precision verified before prepare review and signing');
 await select('fund_bounty');await page.getByLabel('bounty',{exact:true}).selectOption(bounty.id);await prepare();await confirm();assert.equal(prepared.at(-1).amount,bounty.budget,'exact bounty amount controls approval');
 await page.getByText('create a bounty draft',{exact:true}).click();await page.getByLabel('bounty title',{exact:true}).fill('new source check');await page.getByLabel('bounty description',{exact:true}).fill('check the published primary sources');await page.getByLabel('bounty budget in USDT',{exact:true}).fill('1.000000000000000001');await page.getByLabel('bounty deadline',{exact:true}).fill(new Date(Date.now()+86400000).toISOString().slice(0,16));await page.getByRole('button',{name:'save bounty draft',exact:true}).click();await page.getByText('Bounty draft saved. Review its funding transaction when ready.',{exact:true}).waitFor();await prepare();await confirm();assert.equal(prepared.at(-1).bounty_id,'new-bounty');
 await select('grant_session');await page.getByLabel('total authorized USDT',{exact:true}).fill('5');await page.getByLabel('session nonce (optional)',{exact:true}).fill('9007199254740993');await page.locator('fieldset').filter({hasText:'allowed merchant recipients'}).getByRole('checkbox').check();await prepare();await confirm();assert.equal(prepared.at(-1).session_nonce,'9007199254740993');
 await select('revoke_session');await prepare();await confirm();assert.equal(prepared.at(-1).session_nonce,'9007199254740993');
 await select('session_pay');await page.getByLabel('amount in USDT',{exact:true}).fill('0.000000000000000001');await page.locator('select').filter({has:page.locator('option[value="'+contract+'"]')}).selectOption(contract);await page.getByLabel('request commitment',{exact:true}).fill('0x'+'b'.repeat(64));await page.getByLabel('receipt commitment',{exact:true}).fill('0x'+'c'.repeat(64));await prepare();await confirm();assert.equal(prepared.at(-1).action,'session_pay');assert.equal(prepared.at(-1).amount,'0.000000000000000001');
 await select('stake');await page.getByText('This action requires the official TAB token.',{exact:false}).waitFor();assert.equal(await page.getByRole('button',{name:'review wallet action',exact:true}).isDisabled(),true);
 await select('fund_spending');await page.getByLabel('amount in USDT',{exact:true}).fill('1');await prepare();await page.evaluate(()=>document.body.dataset.mode='unknown');await page.getByRole('button',{name:'confirm wallet action',exact:true}).click();await page.getByText('RPC response lost after wallet interaction.',{exact:true}).waitFor();const count=prepared.length;pending=[];await page.reload({waitUntil:'networkidle'});assert.equal(await page.getByRole('button',{name:'confirm wallet action',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'review wallet action',exact:true}).isDisabled(),true);await page.getByLabel('submitted action hash').fill(hash);await page.getByRole('button',{name:'verify wallet action',exact:true}).click();await page.getByText('Wallet action confirmed on BNB Chain.',{exact:true}).waitFor();assert.equal(prepared.length,count,'unknown submission recovery never prepares or sends a second payment');
 await select('fund_spending');await prepare();await page.evaluate(()=>document.body.dataset.mode='unknown');await page.getByRole('button',{name:'confirm wallet action',exact:true}).click();await page.getByText('RPC response lost after wallet interaction.',{exact:true}).waitFor();pending=[];submitted=[];releaseRequiresSubmit=true;await page.reload({waitUntil:'networkidle'});await page.getByLabel('submitted action hash').fill(hash);await page.getByRole('button',{name:'check reverted action',exact:true}).click();await page.getByText('Reverted transaction verified. A new action can be reviewed.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('tab:wallet:pending:agent-a')),null);
 for(const width of [320,390,768]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`wallet tools fit ${width}px`);}assert.deepEqual(errors,[]);assert.ok(confirmations>=9);console.log('Wallet tools: exact token/native amounts, factory/pair/backing/job bind/bond/bounty controls, verified6-decimal bond approvals, official TAB gate, wallet guard mutations, rejection retry and uncertain recovery passed without funds.');
}catch(error){console.error((await page.locator('body').innerText()).slice(-3500));throw error;}finally{await browser.close();}
